// This file is auto-generated by @hey-api/openapi-ts

export const auth_RenewManagerCredentialsInputDTOSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string'
        },
        password: {
            type: 'string'
        }
    }
} as const;

export const auth_RenewManagerInputDTOSchema = {
    type: 'object',
    properties: {
        refresh_token: {
            type: 'string'
        }
    }
} as const;

export const auth_RenewManagerResponseSchema = {
    type: 'object',
    required: ['error', 'msg'],
    properties: {
        error: {
            type: 'boolean'
        },
        msg: {
            type: 'string'
        },
        result: {
            '$ref': '#/definitions/auth.Tokens'
        }
    }
} as const;

export const auth_RenewManagerUserResponseSchema = {
    type: 'object',
    required: ['error', 'msg'],
    properties: {
        error: {
            type: 'boolean'
        },
        msg: {
            type: 'string'
        },
        result: {
            '$ref': '#/definitions/auth.TokenPublicData'
        }
    }
} as const;

export const auth_TokenDataWithExpSchema = {
    type: 'object',
    properties: {
        exp: {
            type: 'integer'
        },
        token: {
            type: 'string'
        }
    }
} as const;

export const auth_TokenPublicDataSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string'
        },
        exp: {
            type: 'integer'
        },
        id: {
            type: 'integer'
        },
        last_launch_id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        role: {
            type: 'string'
        }
    }
} as const;

export const auth_TokensSchema = {
    type: 'object',
    properties: {
        access: {
            '$ref': '#/definitions/auth.TokenDataWithExp'
        },
        refresh: {
            '$ref': '#/definitions/auth.TokenDataWithExp'
        }
    }
} as const;

export const models_LTIAttemptSchema = {
    type: 'object',
    required: ['created_at', 'updated_at', 'updated_at'],
    properties: {
        created_at: {
            type: 'string'
        },
        id: {
            type: 'integer'
        },
        lti_routing_id: {
            type: 'integer'
        },
        pnet_server_id: {
            type: 'integer'
        },
        room_number: {
            type: 'integer'
        },
        updated_at: {
            type: 'string'
        },
        user_id: {
            type: 'integer'
        }
    }
} as const;

export const models_LTIAttemptListItemSchema = {
    type: 'object',
    required: ['created_at', 'updated_at', 'updated_at'],
    properties: {
        created_at: {
            type: 'string'
        },
        id: {
            type: 'integer'
        },
        lti_routing_id: {
            type: 'integer'
        },
        pnet_server_id: {
            type: 'integer'
        },
        updated_at: {
            type: 'string'
        },
        user_id: {
            type: 'integer'
        }
    }
} as const;

export const models_LTIFormSchema = {
    type: 'object',
    required: ['base_uri', 'created_at', 'key_set_uri', 'lti_auth_login_uri', 'lti_auth_token_uri', 'lti_client_id', 'lti_deployment_id', 'name', 'private_key', 'public_key', 'target_link_uri', 'updated_at'],
    properties: {
        base_uri: {
            type: 'string'
        },
        created_at: {
            type: 'string'
        },
        id: {
            type: 'integer'
        },
        key_set_uri: {
            type: 'string'
        },
        lti_auth_login_uri: {
            type: 'string'
        },
        lti_auth_token_uri: {
            type: 'string'
        },
        lti_client_id: {
            type: 'string'
        },
        lti_deployment_id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        private_key: {
            type: 'string'
        },
        public_key: {
            type: 'string'
        },
        target_link_uri: {
            type: 'string'
        },
        updated_at: {
            type: 'string'
        }
    }
} as const;

export const models_LTIFormListItemSchema = {
    type: 'object',
    required: ['created_at', 'lti_client_id', 'lti_deployment_id', 'name', 'updated_at'],
    properties: {
        created_at: {
            type: 'string'
        },
        id: {
            type: 'integer'
        },
        lti_client_id: {
            type: 'string'
        },
        lti_deployment_id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        updated_at: {
            type: 'string'
        }
    }
} as const;

export const models_LTIRoutingSchema = {
    type: 'object',
    required: ['created_at', 'updated_at'],
    properties: {
        collaboration: {
            description: 'Параметры',
            type: 'integer'
        },
        created_at: {
            type: 'string'
        },
        id: {
            type: 'integer'
        },
        lti_description: {
            type: 'string'
        },
        lti_params_task: {
            type: 'string'
        },
        lti_task_id: {
            type: 'string'
        },
        lti_title: {
            description: 'LTI Params',
            type: 'string'
        },
        name: {
            type: 'string'
        },
        pinned_session_minutes: {
            type: 'integer'
        },
        pnet_labs_path: {
            type: 'string'
        },
        pnet_test_path: {
            type: 'string'
        },
        updated_at: {
            type: 'string'
        }
    }
} as const;

export const models_LTIRoutingListItemSchema = {
    type: 'object',
    required: ['created_at', 'updated_at'],
    properties: {
        created_at: {
            type: 'string'
        },
        id: {
            type: 'integer'
        },
        name: {
            type: 'string'
        },
        updated_at: {
            type: 'string'
        }
    }
} as const;

export const models_PNETServerSchema = {
    type: 'object',
    required: ['created_at', 'updated_at'],
    properties: {
        created_at: {
            type: 'string'
        },
        id: {
            type: 'integer'
        },
        is_active: {
            type: 'boolean'
        },
        last_count_users: {
            type: 'integer'
        },
        last_online_status: {
            type: 'string'
        },
        max_count_users_limit: {
            type: 'integer'
        },
        minutes_for_disconnect: {
            type: 'integer'
        },
        name: {
            type: 'string'
        },
        token: {
            type: 'string'
        },
        unit_rate: {
            type: 'integer'
        },
        updated_at: {
            type: 'string'
        },
        url: {
            type: 'string'
        }
    }
} as const;

export const models_PNETServerListItemSchema = {
    type: 'object',
    required: ['created_at', 'updated_at'],
    properties: {
        created_at: {
            type: 'string'
        },
        id: {
            type: 'integer'
        },
        is_active: {
            type: 'boolean'
        },
        last_count_users: {
            type: 'integer'
        },
        last_online_status: {
            type: 'string'
        },
        max_count_users_limit: {
            type: 'integer'
        },
        minutes_for_disconnect: {
            type: 'integer'
        },
        name: {
            type: 'string'
        },
        unit_rate: {
            type: 'integer'
        },
        updated_at: {
            type: 'string'
        },
        url: {
            type: 'string'
        }
    }
} as const;

export const models_UserSchema = {
    type: 'object',
    required: ['created_at', 'group_name', 'updated_at', 'user_role'],
    properties: {
        created_at: {
            type: 'string'
        },
        deleted_at: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        group_name: {
            type: 'string'
        },
        id: {
            type: 'integer'
        },
        last_launch_id: {
            type: 'string'
        },
        lti_user_id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        updated_at: {
            type: 'string'
        },
        user_role: {
            type: 'string'
        }
    }
} as const;

export const models_UserListItemSchema = {
    type: 'object',
    required: ['created_at', 'group_name', 'updated_at', 'user_role'],
    properties: {
        created_at: {
            type: 'string'
        },
        deleted_at: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        group_name: {
            type: 'string'
        },
        id: {
            type: 'integer'
        },
        lti_user_id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        updated_at: {
            type: 'string'
        },
        user_role: {
            type: 'string'
        }
    }
} as const;

export const queries_RoundQueuePoolPnetListItemSchema = {
    type: 'object',
    required: ['connected_at', 'last_used', 'type'],
    properties: {
        connected_at: {
            type: 'string'
        },
        id: {
            type: 'integer'
        },
        last_used: {
            type: 'boolean'
        },
        name: {
            type: 'string'
        },
        type: {
            type: 'string'
        }
    }
} as const;

export const round_queue_pool_pnet_RoundQueuePoolPnetListOutputDTOSchema = {
    type: 'object',
    required: ['model'],
    properties: {
        model: {
            type: 'array',
            items: {
                '$ref': '#/definitions/queries.RoundQueuePoolPnetListItem'
            }
        }
    }
} as const;

export const round_queue_pool_pnet_RoundQueuePoolPnetListResponseSchema = {
    type: 'object',
    required: ['error', 'msg'],
    properties: {
        error: {
            type: 'boolean'
        },
        msg: {
            type: 'string'
        },
        result: {
            '$ref': '#/definitions/round_queue_pool_pnet.RoundQueuePoolPnetListOutputDTO'
        }
    }
} as const;

export const round_queue_pool_pnet_RoundQueuePoolPnetUpsertOutputDTOSchema = {
    type: 'object'
} as const;

export const round_queue_pool_pnet_RoundQueuePoolPnetUpsertResponseSchema = {
    type: 'object',
    required: ['error', 'msg'],
    properties: {
        error: {
            type: 'boolean'
        },
        msg: {
            type: 'string'
        },
        result: {
            '$ref': '#/definitions/round_queue_pool_pnet.RoundQueuePoolPnetUpsertOutputDTO'
        }
    }
} as const;

export const usecases_LTIAttemptCreateInputDTOSchema = {
    type: 'object'
} as const;

export const usecases_LTIAttemptCreateOutputDTOSchema = {
    type: 'object',
    properties: {
        auto_redirect: {
            type: 'boolean'
        },
        collaboration: {
            type: 'integer'
        },
        members: {
            type: 'array',
            items: {
                '$ref': '#/definitions/models.UserListItem'
            }
        },
        next_url: {
            type: 'string'
        },
        room_number: {
            type: 'integer'
        }
    }
} as const;

export const usecases_LTIAttemptCreateResponseSchema = {
    type: 'object',
    required: ['error', 'msg'],
    properties: {
        error: {
            type: 'boolean'
        },
        msg: {
            type: 'string'
        },
        result: {
            '$ref': '#/definitions/usecases.LTIAttemptCreateOutputDTO'
        }
    }
} as const;

export const usecases_LTIAttemptDeleteInputDTOSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer'
        }
    }
} as const;

export const usecases_LTIAttemptDeleteResponseSchema = {
    type: 'object',
    required: ['error', 'msg'],
    properties: {
        error: {
            type: 'boolean'
        },
        msg: {
            type: 'string'
        },
        result: {
            '$ref': '#/definitions/usecases.LTIAttemptDeleteInputDTO'
        }
    }
} as const;

export const usecases_LTIAttemptEditInputDTOSchema = {
    type: 'object',
    required: ['name', 'token', 'url'],
    properties: {
        id: {
            type: 'integer'
        },
        is_active: {
            type: 'boolean'
        },
        name: {
            type: 'string'
        },
        token: {
            type: 'string'
        },
        unit_rate: {
            type: 'integer'
        },
        url: {
            type: 'string'
        }
    }
} as const;

export const usecases_LTIAttemptEditOutputDTOSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer'
        }
    }
} as const;

export const usecases_LTIAttemptEditResponseSchema = {
    type: 'object',
    required: ['error', 'msg'],
    properties: {
        error: {
            type: 'boolean'
        },
        msg: {
            type: 'string'
        },
        result: {
            '$ref': '#/definitions/usecases.LTIAttemptEditOutputDTO'
        }
    }
} as const;

export const usecases_LTIAttemptGetInputDTOSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer'
        }
    }
} as const;

export const usecases_LTIAttemptGetOutputDTOSchema = {
    type: 'object',
    properties: {
        model: {
            '$ref': '#/definitions/models.LTIAttempt'
        }
    }
} as const;

export const usecases_LTIAttemptGetResponseSchema = {
    type: 'object',
    required: ['error', 'msg'],
    properties: {
        error: {
            type: 'boolean'
        },
        msg: {
            type: 'string'
        },
        result: {
            '$ref': '#/definitions/usecases.LTIAttemptGetOutputDTO'
        }
    }
} as const;

export const usecases_LTIAttemptListInputDTOSchema = {
    type: 'object',
    properties: {
        limit: {
            type: 'integer'
        },
        offset: {
            type: 'integer'
        },
        search: {
            type: 'string'
        }
    }
} as const;

export const usecases_LTIAttemptListOutputDTOSchema = {
    type: 'object',
    required: ['model', 'total_count'],
    properties: {
        model: {
            type: 'array',
            items: {
                '$ref': '#/definitions/models.LTIAttemptListItem'
            }
        },
        total_count: {
            type: 'integer'
        }
    }
} as const;

export const usecases_LTIAttemptListResponseSchema = {
    type: 'object',
    required: ['error', 'msg'],
    properties: {
        error: {
            type: 'boolean'
        },
        msg: {
            type: 'string'
        },
        result: {
            '$ref': '#/definitions/usecases.LTIAttemptListOutputDTO'
        }
    }
} as const;

export const usecases_LTIFormDeleteInputDTOSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer'
        }
    }
} as const;

export const usecases_LTIFormDeleteResponseSchema = {
    type: 'object',
    required: ['error', 'msg'],
    properties: {
        error: {
            type: 'boolean'
        },
        msg: {
            type: 'string'
        },
        result: {
            '$ref': '#/definitions/usecases.LTIFormDeleteInputDTO'
        }
    }
} as const;

export const usecases_LTIFormEditInputDTOSchema = {
    type: 'object',
    required: ['auth_login_uri', 'auth_token_uri', 'base_uri', 'client_id', 'deployment_id', 'key_set_uri', 'name', 'target_link_uri'],
    properties: {
        auth_login_uri: {
            type: 'string'
        },
        auth_token_uri: {
            type: 'string'
        },
        base_uri: {
            type: 'string'
        },
        client_id: {
            type: 'string'
        },
        deployment_id: {
            type: 'string'
        },
        id: {
            type: 'integer'
        },
        key_set_uri: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        target_link_uri: {
            type: 'string'
        }
    }
} as const;

export const usecases_LTIFormEditOutputDTOSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer'
        }
    }
} as const;

export const usecases_LTIFormEditResponseSchema = {
    type: 'object',
    required: ['error', 'msg'],
    properties: {
        error: {
            type: 'boolean'
        },
        msg: {
            type: 'string'
        },
        result: {
            '$ref': '#/definitions/usecases.LTIFormEditOutputDTO'
        }
    }
} as const;

export const usecases_LTIFormGetInputDTOSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer'
        }
    }
} as const;

export const usecases_LTIFormGetOutputDTOSchema = {
    type: 'object',
    properties: {
        model: {
            '$ref': '#/definitions/models.LTIForm'
        }
    }
} as const;

export const usecases_LTIFormGetResponseSchema = {
    type: 'object',
    required: ['error', 'msg'],
    properties: {
        error: {
            type: 'boolean'
        },
        msg: {
            type: 'string'
        },
        result: {
            '$ref': '#/definitions/usecases.LTIFormGetOutputDTO'
        }
    }
} as const;

export const usecases_LTIFormListInputDTOSchema = {
    type: 'object',
    properties: {
        limit: {
            type: 'integer'
        },
        offset: {
            type: 'integer'
        },
        search: {
            type: 'string'
        }
    }
} as const;

export const usecases_LTIFormListOutputDTOSchema = {
    type: 'object',
    required: ['model', 'total_count'],
    properties: {
        model: {
            type: 'array',
            items: {
                '$ref': '#/definitions/models.LTIFormListItem'
            }
        },
        total_count: {
            type: 'integer'
        }
    }
} as const;

export const usecases_LTIFormListResponseSchema = {
    type: 'object',
    required: ['error', 'msg'],
    properties: {
        error: {
            type: 'boolean'
        },
        msg: {
            type: 'string'
        },
        result: {
            '$ref': '#/definitions/usecases.LTIFormListOutputDTO'
        }
    }
} as const;

export const usecases_LTIRoutingDeleteInputDTOSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer'
        }
    }
} as const;

export const usecases_LTIRoutingDeleteResponseSchema = {
    type: 'object',
    required: ['error', 'msg'],
    properties: {
        error: {
            type: 'boolean'
        },
        msg: {
            type: 'string'
        },
        result: {
            '$ref': '#/definitions/usecases.LTIRoutingDeleteInputDTO'
        }
    }
} as const;

export const usecases_LTIRoutingEditInputDTOSchema = {
    type: 'object',
    properties: {
        collaboration: {
            type: 'integer'
        },
        id: {
            type: 'integer'
        },
        lti_description: {
            type: 'string'
        },
        lti_params_task: {
            type: 'string'
        },
        lti_task_id: {
            type: 'string'
        },
        lti_title: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        pinned_session_minutes: {
            type: 'integer'
        },
        pnet_labs_path: {
            type: 'string'
        },
        pnet_test_path: {
            type: 'string'
        }
    }
} as const;

export const usecases_LTIRoutingEditOutputDTOSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer'
        }
    }
} as const;

export const usecases_LTIRoutingEditResponseSchema = {
    type: 'object',
    required: ['error', 'msg'],
    properties: {
        error: {
            type: 'boolean'
        },
        msg: {
            type: 'string'
        },
        result: {
            '$ref': '#/definitions/usecases.LTIRoutingEditOutputDTO'
        }
    }
} as const;

export const usecases_LTIRoutingGetInputDTOSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer'
        }
    }
} as const;

export const usecases_LTIRoutingGetOutputDTOSchema = {
    type: 'object',
    properties: {
        model: {
            '$ref': '#/definitions/models.LTIRouting'
        }
    }
} as const;

export const usecases_LTIRoutingGetResponseSchema = {
    type: 'object',
    required: ['error', 'msg'],
    properties: {
        error: {
            type: 'boolean'
        },
        msg: {
            type: 'string'
        },
        result: {
            '$ref': '#/definitions/usecases.LTIRoutingGetOutputDTO'
        }
    }
} as const;

export const usecases_LTIRoutingListInputDTOSchema = {
    type: 'object',
    properties: {
        limit: {
            type: 'integer'
        },
        offset: {
            type: 'integer'
        },
        search: {
            type: 'string'
        }
    }
} as const;

export const usecases_LTIRoutingListOutputDTOSchema = {
    type: 'object',
    required: ['model', 'total_count'],
    properties: {
        model: {
            type: 'array',
            items: {
                '$ref': '#/definitions/models.LTIRoutingListItem'
            }
        },
        total_count: {
            type: 'integer'
        }
    }
} as const;

export const usecases_LTIRoutingListResponseSchema = {
    type: 'object',
    required: ['error', 'msg'],
    properties: {
        error: {
            type: 'boolean'
        },
        msg: {
            type: 'string'
        },
        result: {
            '$ref': '#/definitions/usecases.LTIRoutingListOutputDTO'
        }
    }
} as const;

export const usecases_PNETServerDeleteInputDTOSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer'
        }
    }
} as const;

export const usecases_PNETServerDeleteResponseSchema = {
    type: 'object',
    required: ['error', 'msg'],
    properties: {
        error: {
            type: 'boolean'
        },
        msg: {
            type: 'string'
        },
        result: {
            '$ref': '#/definitions/usecases.PNETServerDeleteInputDTO'
        }
    }
} as const;

export const usecases_PNETServerEditInputDTOSchema = {
    type: 'object',
    required: ['name', 'url'],
    properties: {
        id: {
            type: 'integer'
        },
        is_active: {
            type: 'boolean'
        },
        max_count_users_limit: {
            type: 'integer'
        },
        minutes_for_disconnect: {
            type: 'integer'
        },
        name: {
            type: 'string'
        },
        unit_rate: {
            type: 'integer'
        },
        url: {
            type: 'string'
        }
    }
} as const;

export const usecases_PNETServerEditOutputDTOSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer'
        }
    }
} as const;

export const usecases_PNETServerEditResponseSchema = {
    type: 'object',
    required: ['error', 'msg'],
    properties: {
        error: {
            type: 'boolean'
        },
        msg: {
            type: 'string'
        },
        result: {
            '$ref': '#/definitions/usecases.PNETServerEditOutputDTO'
        }
    }
} as const;

export const usecases_PNETServerGetInputDTOSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer'
        }
    }
} as const;

export const usecases_PNETServerGetOutputDTOSchema = {
    type: 'object',
    properties: {
        model: {
            '$ref': '#/definitions/models.PNETServer'
        }
    }
} as const;

export const usecases_PNETServerGetResponseSchema = {
    type: 'object',
    required: ['error', 'msg'],
    properties: {
        error: {
            type: 'boolean'
        },
        msg: {
            type: 'string'
        },
        result: {
            '$ref': '#/definitions/usecases.PNETServerGetOutputDTO'
        }
    }
} as const;

export const usecases_PNETServerListInputDTOSchema = {
    type: 'object',
    properties: {
        limit: {
            type: 'integer'
        },
        offset: {
            type: 'integer'
        },
        order_by: {
            description: `The type of orderBy
enum: createdAt,unitRate,lastCountUsers`,
            type: 'string'
        },
        search: {
            type: 'string'
        },
        status: {
            description: `The type of status
enum: all,active`,
            type: 'string'
        }
    }
} as const;

export const usecases_PNETServerListOutputDTOSchema = {
    type: 'object',
    required: ['model', 'total_count'],
    properties: {
        model: {
            type: 'array',
            items: {
                '$ref': '#/definitions/models.PNETServerListItem'
            }
        },
        total_count: {
            type: 'integer'
        }
    }
} as const;

export const usecases_PNETServerListResponseSchema = {
    type: 'object',
    required: ['error', 'msg'],
    properties: {
        error: {
            type: 'boolean'
        },
        msg: {
            type: 'string'
        },
        result: {
            '$ref': '#/definitions/usecases.PNETServerListOutputDTO'
        }
    }
} as const;

export const usecases_UserEditInputDTOSchema = {
    type: 'object',
    required: ['email', 'name'],
    properties: {
        email: {
            type: 'string'
        },
        group_name: {
            type: 'string'
        },
        id: {
            type: 'integer'
        },
        is_active: {
            type: 'boolean'
        },
        lti_user_id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        user_role: {
            type: 'string'
        }
    }
} as const;

export const usecases_UserEditOutputDTOSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer'
        }
    }
} as const;

export const usecases_UserEditResponseSchema = {
    type: 'object',
    required: ['error', 'msg'],
    properties: {
        error: {
            type: 'boolean'
        },
        msg: {
            type: 'string'
        },
        result: {
            '$ref': '#/definitions/usecases.UserEditOutputDTO'
        }
    }
} as const;

export const usecases_UserGetInputDTOSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer'
        }
    }
} as const;

export const usecases_UserGetOutputDTOSchema = {
    type: 'object',
    properties: {
        model: {
            '$ref': '#/definitions/models.User'
        }
    }
} as const;

export const usecases_UserGetResponseSchema = {
    type: 'object',
    required: ['error', 'msg'],
    properties: {
        error: {
            type: 'boolean'
        },
        msg: {
            type: 'string'
        },
        result: {
            '$ref': '#/definitions/usecases.UserGetOutputDTO'
        }
    }
} as const;

export const usecases_UserListInputDTOSchema = {
    type: 'object',
    properties: {
        limit: {
            type: 'integer'
        },
        offset: {
            type: 'integer'
        },
        search: {
            type: 'string'
        }
    }
} as const;

export const usecases_UserListOutputDTOSchema = {
    type: 'object',
    required: ['model', 'total_count'],
    properties: {
        model: {
            type: 'array',
            items: {
                '$ref': '#/definitions/models.UserListItem'
            }
        },
        total_count: {
            type: 'integer'
        }
    }
} as const;

export const usecases_UserListResponseSchema = {
    type: 'object',
    required: ['error', 'msg'],
    properties: {
        error: {
            type: 'boolean'
        },
        msg: {
            type: 'string'
        },
        result: {
            '$ref': '#/definitions/usecases.UserListOutputDTO'
        }
    }
} as const;

export const usecases_UserPasswordChangeInputDTOSchema = {
    type: 'object',
    properties: {
        again_password: {
            type: 'string'
        },
        new_password: {
            type: 'string'
        },
        old_password: {
            type: 'string'
        }
    }
} as const;

export const usecases_UserPasswordChangeOutputDTOSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer'
        }
    }
} as const;

export const usecases_UserPasswordRecoverResponseSchema = {
    type: 'object',
    required: ['error', 'msg'],
    properties: {
        error: {
            type: 'boolean'
        },
        msg: {
            type: 'string'
        },
        result: {
            '$ref': '#/definitions/usecases.UserPasswordChangeOutputDTO'
        }
    }
} as const;