// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { PostV1LtiAttemptCreateData, PostV1LtiAttemptCreateResponse, PostV1LtiAttemptDeleteData, PostV1LtiAttemptDeleteResponse, PostV1LtiAttemptEditData, PostV1LtiAttemptEditResponse, PostV1LtiAttemptGetData, PostV1LtiAttemptGetResponse, PostV1LtiAttemptListData, PostV1LtiAttemptListResponse, PostV1LtiFormDeleteData, PostV1LtiFormDeleteResponse, PostV1LtiFormGetData, PostV1LtiFormGetResponse, PostV1LtiFormListData, PostV1LtiFormListResponse, PostV1LtiFormUpsertData, PostV1LtiFormUpsertResponse, PostV1LtiRoutingDeleteData, PostV1LtiRoutingDeleteResponse, PostV1LtiRoutingGetData, PostV1LtiRoutingGetResponse, PostV1LtiRoutingListData, PostV1LtiRoutingListResponse, PostV1LtiRoutingUpsertData, PostV1LtiRoutingUpsertResponse, PostV1PnetServerQueueListResponse, PostV1PnetServerQueueUpsertResponse, PostV1PnetServerDeleteData, PostV1PnetServerDeleteResponse, PostV1PnetServerGetData, PostV1PnetServerGetResponse, PostV1PnetServerListData, PostV1PnetServerListResponse, PostV1PnetServerUpsertData, PostV1PnetServerUpsertResponse, PostV1TokenCheckData, PostV1TokenCheckResponse, PostV1TokenLoginData, PostV1TokenLoginResponse, PostV1TokenLogoutResponse, PostV1TokenPasswordChangeData, PostV1TokenPasswordChangeResponse, PostV1TokenRenewData, PostV1TokenRenewResponse, PostV1UserGetData, PostV1UserGetResponse, PostV1UserListData, PostV1UserListResponse, PostV1UserUpsertData, PostV1UserUpsertResponse, GetV2LtiLoginResponse, PostV2LtiLoginResponse } from './types.gen';

/**
 * create lti_attempt
 * Create or get exists lti_attempt. Roles: [admin, instructor, student]
 * @param data The data for the request.
 * @param data.form lti_attempt form info
 * @returns usecases_LTIAttemptCreateResponse OK
 * @throws ApiError
 */
export const postV1LtiAttemptCreate = (data: PostV1LtiAttemptCreateData): CancelablePromise<PostV1LtiAttemptCreateResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/v1/lti-attempt/create',
    body: data.form
}); };

/**
 * delete lti_attempt
 * Delete lti_attempt.
 * @param data The data for the request.
 * @param data.form lti_attempt id
 * @returns usecases_LTIAttemptDeleteResponse OK
 * @throws ApiError
 */
export const postV1LtiAttemptDelete = (data: PostV1LtiAttemptDeleteData): CancelablePromise<PostV1LtiAttemptDeleteResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/v1/lti-attempt/delete',
    body: data.form
}); };

/**
 * edit lti_attempt
 * Edit lti_attempt.
 * @param data The data for the request.
 * @param data.form lti_attempt form info
 * @returns usecases_LTIAttemptEditResponse OK
 * @throws ApiError
 */
export const postV1LtiAttemptEdit = (data: PostV1LtiAttemptEditData): CancelablePromise<PostV1LtiAttemptEditResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/v1/lti-attempt/edit',
    body: data.form
}); };

/**
 * get lti_attempt
 * get lti_attempt.
 * @param data The data for the request.
 * @param data.form lti_attempt id
 * @returns usecases_LTIAttemptGetResponse OK
 * @throws ApiError
 */
export const postV1LtiAttemptGet = (data: PostV1LtiAttemptGetData): CancelablePromise<PostV1LtiAttemptGetResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/v1/lti-attempt/get',
    body: data.form
}); };

/**
 * list lti_attempt
 * List lti_attempt.
 * @param data The data for the request.
 * @param data.form lti_attempt list info
 * @returns usecases_LTIAttemptListResponse OK
 * @throws ApiError
 */
export const postV1LtiAttemptList = (data: PostV1LtiAttemptListData): CancelablePromise<PostV1LtiAttemptListResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/v1/lti-attempt/list',
    body: data.form
}); };

/**
 * delete lti_form
 * Delete lti_form. Roles: [admin]
 * @param data The data for the request.
 * @param data.form lti_form id
 * @returns usecases_LTIFormDeleteResponse OK
 * @throws ApiError
 */
export const postV1LtiFormDelete = (data: PostV1LtiFormDeleteData): CancelablePromise<PostV1LtiFormDeleteResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/v1/lti-form/delete',
    body: data.form
}); };

/**
 * get lti_form
 * get lti_form. Roles [admin]
 * @param data The data for the request.
 * @param data.form lti_form id
 * @returns usecases_LTIFormGetResponse OK
 * @throws ApiError
 */
export const postV1LtiFormGet = (data: PostV1LtiFormGetData): CancelablePromise<PostV1LtiFormGetResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/v1/lti-form/get',
    body: data.form
}); };

/**
 * list lti_form
 * List lti_form. Roles: [admin]
 * @param data The data for the request.
 * @param data.form lti_form list info
 * @returns usecases_LTIFormListResponse OK
 * @throws ApiError
 */
export const postV1LtiFormList = (data: PostV1LtiFormListData): CancelablePromise<PostV1LtiFormListResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/v1/lti-form/list',
    body: data.form
}); };

/**
 * create lti_form
 * Create lti_form. Roles: [admin]
 * @param data The data for the request.
 * @param data.form lti_form form info
 * @returns usecases_LTIFormEditResponse OK
 * @throws ApiError
 */
export const postV1LtiFormUpsert = (data: PostV1LtiFormUpsertData): CancelablePromise<PostV1LtiFormUpsertResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/v1/lti-form/upsert',
    body: data.form
}); };

/**
 * delete lti_routing
 * Delete lti_routing. Roles [admin, instructor]
 * @param data The data for the request.
 * @param data.form lti_routing id
 * @returns usecases_LTIRoutingDeleteResponse OK
 * @throws ApiError
 */
export const postV1LtiRoutingDelete = (data: PostV1LtiRoutingDeleteData): CancelablePromise<PostV1LtiRoutingDeleteResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/v1/lti-routing/delete',
    body: data.form
}); };

/**
 * get lti_routing
 * get lti_routing. Roles [admin, instructor]
 * @param data The data for the request.
 * @param data.form lti_routing id
 * @returns usecases_LTIRoutingGetResponse OK
 * @throws ApiError
 */
export const postV1LtiRoutingGet = (data: PostV1LtiRoutingGetData): CancelablePromise<PostV1LtiRoutingGetResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/v1/lti-routing/get',
    body: data.form
}); };

/**
 * list lti_routing
 * List lti_routing. Roles [admin, instructor]
 * @param data The data for the request.
 * @param data.form lti_routing list info
 * @returns usecases_LTIRoutingListResponse OK
 * @throws ApiError
 */
export const postV1LtiRoutingList = (data: PostV1LtiRoutingListData): CancelablePromise<PostV1LtiRoutingListResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/v1/lti-routing/list',
    body: data.form
}); };

/**
 * create lti_routing
 * Create lti_routing. Roles [admin, instructor]
 * @param data The data for the request.
 * @param data.form lti_routing form info
 * @returns usecases_LTIRoutingEditResponse OK
 * @throws ApiError
 */
export const postV1LtiRoutingUpsert = (data: PostV1LtiRoutingUpsertData): CancelablePromise<PostV1LtiRoutingUpsertResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/v1/lti-routing/upsert',
    body: data.form
}); };

/**
 * list pnet_server_queue
 * List pnet_server_queue. Roles: [admin, instructor]
 * @returns round_queue_pool_pnet_RoundQueuePoolPnetListResponse OK
 * @throws ApiError
 */
export const postV1PnetServerQueueList = (): CancelablePromise<PostV1PnetServerQueueListResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/v1/pnet-server-queue/list'
}); };

/**
 * create pnet_server_queue
 * Create pnet_server_queue. Roles: [admin, instructor]
 * @returns round_queue_pool_pnet_RoundQueuePoolPnetUpsertResponse OK
 * @throws ApiError
 */
export const postV1PnetServerQueueUpsert = (): CancelablePromise<PostV1PnetServerQueueUpsertResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/v1/pnet-server-queue/upsert'
}); };

/**
 * delete pnet_server
 * Delete pnet_server. Roles: [admin]
 * @param data The data for the request.
 * @param data.form pnet_server id
 * @returns usecases_PNETServerDeleteResponse OK
 * @throws ApiError
 */
export const postV1PnetServerDelete = (data: PostV1PnetServerDeleteData): CancelablePromise<PostV1PnetServerDeleteResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/v1/pnet-server/delete',
    body: data.form
}); };

/**
 * get pnet_server
 * get pnet_server. Roles: [admin, instructor]
 * @param data The data for the request.
 * @param data.form pnet_server id
 * @returns usecases_PNETServerGetResponse OK
 * @throws ApiError
 */
export const postV1PnetServerGet = (data: PostV1PnetServerGetData): CancelablePromise<PostV1PnetServerGetResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/v1/pnet-server/get',
    body: data.form
}); };

/**
 * list pnet_server
 * List pnet_server. Roles: [admin, instructor]
 * @param data The data for the request.
 * @param data.form pnet_server list info
 * @returns usecases_PNETServerListResponse OK
 * @throws ApiError
 */
export const postV1PnetServerList = (data: PostV1PnetServerListData): CancelablePromise<PostV1PnetServerListResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/v1/pnet-server/list',
    body: data.form
}); };

/**
 * create pnet_server
 * Create pnet_server. Roles [admin]
 * @param data The data for the request.
 * @param data.form pnet_server form info
 * @returns usecases_PNETServerEditResponse OK
 * @throws ApiError
 */
export const postV1PnetServerUpsert = (data: PostV1PnetServerUpsertData): CancelablePromise<PostV1PnetServerUpsertResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/v1/pnet-server/upsert',
    body: data.form
}); };

/**
 * view data from access token
 * View data access token.
 * @param data The data for the request.
 * @param data.form renew token form info
 * @returns auth_RenewManagerUserResponse OK
 * @throws ApiError
 */
export const postV1TokenCheck = (data: PostV1TokenCheckData): CancelablePromise<PostV1TokenCheckResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/v1/token/check',
    body: data.form
}); };

/**
 * login by email and password
 * Login by email and password.
 * @param data The data for the request.
 * @param data.form credentials form info
 * @returns auth_RenewManagerResponse OK
 * @throws ApiError
 */
export const postV1TokenLogin = (data: PostV1TokenLoginData): CancelablePromise<PostV1TokenLoginResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/v1/token/login',
    body: data.form
}); };

/**
 * logout
 * Logout.
 * @returns auth_RenewManagerResponse OK
 * @throws ApiError
 */
export const postV1TokenLogout = (): CancelablePromise<PostV1TokenLogoutResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/v1/token/logout'
}); };

/**
 * change password
 * Change password.
 * @param data The data for the request.
 * @param data.form credentials form info
 * @returns usecases_UserPasswordRecoverResponse OK
 * @throws ApiError
 */
export const postV1TokenPasswordChange = (data: PostV1TokenPasswordChangeData): CancelablePromise<PostV1TokenPasswordChangeResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/v1/token/password_change',
    body: data.form
}); };

/**
 * renew access and refresh tokens
 * Renew access and refresh tokens.
 * @param data The data for the request.
 * @param data.form renew token form info
 * @returns auth_RenewManagerResponse OK
 * @throws ApiError
 */
export const postV1TokenRenew = (data: PostV1TokenRenewData): CancelablePromise<PostV1TokenRenewResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/v1/token/renew',
    body: data.form
}); };

/**
 * get user
 * get user. Roles[admin, instructor]
 * @param data The data for the request.
 * @param data.form user id
 * @returns usecases_UserGetResponse OK
 * @throws ApiError
 */
export const postV1UserGet = (data: PostV1UserGetData): CancelablePromise<PostV1UserGetResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/v1/user/get',
    body: data.form
}); };

/**
 * list user
 * List user. Roles[admin, instructor]
 * @param data The data for the request.
 * @param data.form user list info
 * @returns usecases_UserListResponse OK
 * @throws ApiError
 */
export const postV1UserList = (data: PostV1UserListData): CancelablePromise<PostV1UserListResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/v1/user/list',
    body: data.form
}); };

/**
 * create user
 * Create user. Roles[admin, instructor]
 * @param data The data for the request.
 * @param data.form user form info
 * @returns usecases_UserEditResponse OK
 * @throws ApiError
 */
export const postV1UserUpsert = (data: PostV1UserUpsertData): CancelablePromise<PostV1UserUpsertResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/v1/user/upsert',
    body: data.form
}); };

/**
 * инициализация подключения к LTI
 * инициализация подключения к LTI.
 * @throws ApiError
 */
export const getV2LtiLaunch = (): CancelablePromise<void> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/v2/lti/launch',
    errors: {
        302: 'Found'
    }
}); };

/**
 * инициализация подключения к LTI
 * инициализация подключения к LTI.
 * @throws ApiError
 */
export const postV2LtiLaunch = (): CancelablePromise<void> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/v2/lti/launch',
    errors: {
        302: 'Found'
    }
}); };

/**
 * аутентификация через LTI
 * аутентификация LTI.
 * @returns unknown OK
 * @throws ApiError
 */
export const getV2LtiLogin = (): CancelablePromise<GetV2LtiLoginResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/v2/lti/login'
}); };

/**
 * аутентификация через LTI
 * аутентификация LTI.
 * @returns unknown OK
 * @throws ApiError
 */
export const postV2LtiLogin = (): CancelablePromise<PostV2LtiLoginResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/v2/lti/login'
}); };