// This file is auto-generated by @hey-api/openapi-ts

export type auth_RenewManagerCredentialsInputDTO = {
    email?: string;
    password?: string;
};

export type auth_RenewManagerInputDTO = {
    refresh_token?: string;
};

export type auth_RenewManagerResponse = {
    error: boolean;
    msg: string;
    result?: auth_Tokens;
};

export type auth_RenewManagerUserResponse = {
    error: boolean;
    msg: string;
    result?: auth_TokenPublicData;
};

export type auth_TokenDataWithExp = {
    exp?: number;
    token?: string;
};

export type auth_TokenPublicData = {
    email?: string;
    exp?: number;
    id?: number;
    last_launch_id?: string;
    name?: string;
    role?: string;
};

export type auth_Tokens = {
    access?: auth_TokenDataWithExp;
    refresh?: auth_TokenDataWithExp;
};

export type models_LTIForm = {
    base_uri: string;
    created_at: string;
    id?: number;
    key_set_uri: string;
    lti_auth_login_uri: string;
    lti_auth_token_uri: string;
    lti_client_id: string;
    lti_deployment_id: string;
    name: string;
    private_key: string;
    public_key: string;
    target_link_uri: string;
    updated_at: string;
};

export type models_LTIFormListItem = {
    created_at: string;
    id?: number;
    lti_client_id: string;
    lti_deployment_id: string;
    name: string;
    updated_at: string;
};

export type models_PNETServer = {
    created_at: string;
    id?: number;
    is_active?: boolean;
    last_online_status?: string;
    minutes_for_disconnect?: number;
    name?: string;
    token?: string;
    unit_rate?: number;
    updated_at: string;
    url?: string;
};

export type models_PNETServerListItem = {
    created_at: string;
    id?: number;
    is_active?: boolean;
    last_online_status?: string;
    minutes_for_disconnect?: number;
    name?: string;
    unit_rate?: number;
    updated_at: string;
    url?: string;
};

export type models_User = {
    created_at: string;
    deleted_at?: string;
    email?: string;
    group_name: string;
    id?: number;
    last_launch_id?: string;
    lti_user_id?: string;
    name?: string;
    updated_at: string;
    user_role: string;
};

export type models_UserListItem = {
    created_at: string;
    deleted_at?: string;
    email?: string;
    group_name: string;
    id?: number;
    lti_user_id?: string;
    name?: string;
    updated_at: string;
    user_role: string;
};

export type usecases_LTIFormDeleteInputDTO = {
    id?: number;
};

export type usecases_LTIFormDeleteResponse = {
    error: boolean;
    msg: string;
    result?: usecases_LTIFormDeleteInputDTO;
};

export type usecases_LTIFormEditInputDTO = {
    auth_login_uri: string;
    auth_token_uri: string;
    base_uri: string;
    client_id: string;
    deployment_id: string;
    id?: number;
    key_set_uri: string;
    name: string;
    target_link_uri: string;
};

export type usecases_LTIFormEditOutputDTO = {
    id?: number;
};

export type usecases_LTIFormEditResponse = {
    error: boolean;
    msg: string;
    result?: usecases_LTIFormEditOutputDTO;
};

export type usecases_LTIFormGetInputDTO = {
    id?: number;
};

export type usecases_LTIFormGetOutputDTO = {
    model?: models_LTIForm;
};

export type usecases_LTIFormGetResponse = {
    error: boolean;
    msg: string;
    result?: usecases_LTIFormGetOutputDTO;
};

export type usecases_LTIFormListInputDTO = {
    limit?: number;
    offset?: number;
    search?: string;
};

export type usecases_LTIFormListOutputDTO = {
    model: Array<models_LTIFormListItem>;
    total_count: number;
};

export type usecases_LTIFormListResponse = {
    error: boolean;
    msg: string;
    result?: usecases_LTIFormListOutputDTO;
};

export type usecases_PNETServerDeleteInputDTO = {
    id?: number;
};

export type usecases_PNETServerDeleteResponse = {
    error: boolean;
    msg: string;
    result?: usecases_PNETServerDeleteInputDTO;
};

export type usecases_PNETServerEditInputDTO = {
    id?: number;
    is_active?: boolean;
    minutes_for_disconnect?: number;
    name: string;
    unit_rate?: number;
    url: string;
};

export type usecases_PNETServerEditOutputDTO = {
    id?: number;
};

export type usecases_PNETServerEditResponse = {
    error: boolean;
    msg: string;
    result?: usecases_PNETServerEditOutputDTO;
};

export type usecases_PNETServerGetInputDTO = {
    id?: number;
};

export type usecases_PNETServerGetOutputDTO = {
    model?: models_PNETServer;
};

export type usecases_PNETServerGetResponse = {
    error: boolean;
    msg: string;
    result?: usecases_PNETServerGetOutputDTO;
};

export type usecases_PNETServerListInputDTO = {
    limit?: number;
    offset?: number;
    search?: string;
};

export type usecases_PNETServerListOutputDTO = {
    model: Array<models_PNETServerListItem>;
    total_count: number;
};

export type usecases_PNETServerListResponse = {
    error: boolean;
    msg: string;
    result?: usecases_PNETServerListOutputDTO;
};

export type usecases_UserEditInputDTO = {
    email: string;
    group_name?: string;
    id?: number;
    is_active?: boolean;
    lti_user_id?: string;
    name: string;
    user_role?: string;
};

export type usecases_UserEditOutputDTO = {
    id?: number;
};

export type usecases_UserEditResponse = {
    error: boolean;
    msg: string;
    result?: usecases_UserEditOutputDTO;
};

export type usecases_UserGetInputDTO = {
    id?: number;
};

export type usecases_UserGetOutputDTO = {
    model?: models_User;
};

export type usecases_UserGetResponse = {
    error: boolean;
    msg: string;
    result?: usecases_UserGetOutputDTO;
};

export type usecases_UserListInputDTO = {
    limit?: number;
    offset?: number;
    search?: string;
};

export type usecases_UserListOutputDTO = {
    model: Array<models_UserListItem>;
    total_count: number;
};

export type usecases_UserListResponse = {
    error: boolean;
    msg: string;
    result?: usecases_UserListOutputDTO;
};

export type usecases_UserPasswordChangeInputDTO = {
    again_password?: string;
    new_password?: string;
    old_password?: string;
};

export type usecases_UserPasswordChangeOutputDTO = {
    id?: number;
};

export type usecases_UserPasswordRecoverResponse = {
    error: boolean;
    msg: string;
    result?: usecases_UserPasswordChangeOutputDTO;
};

export type PostV1LtiFormDeleteData = {
    /**
     * lti_form id
     */
    form: usecases_LTIFormDeleteInputDTO;
};

export type PostV1LtiFormDeleteResponse = (usecases_LTIFormDeleteResponse);

export type PostV1LtiFormGetData = {
    /**
     * lti_form id
     */
    form: usecases_LTIFormGetInputDTO;
};

export type PostV1LtiFormGetResponse = (usecases_LTIFormGetResponse);

export type PostV1LtiFormListData = {
    /**
     * lti_form list info
     */
    form: usecases_LTIFormListInputDTO;
};

export type PostV1LtiFormListResponse = (usecases_LTIFormListResponse);

export type PostV1LtiFormUpsertData = {
    /**
     * lti_form form info
     */
    form: usecases_LTIFormEditInputDTO;
};

export type PostV1LtiFormUpsertResponse = (usecases_LTIFormEditResponse);

export type PostV1PnetServerDeleteData = {
    /**
     * pnet_server id
     */
    form: usecases_PNETServerDeleteInputDTO;
};

export type PostV1PnetServerDeleteResponse = (usecases_PNETServerDeleteResponse);

export type PostV1PnetServerGetData = {
    /**
     * pnet_server id
     */
    form: usecases_PNETServerGetInputDTO;
};

export type PostV1PnetServerGetResponse = (usecases_PNETServerGetResponse);

export type PostV1PnetServerListData = {
    /**
     * pnet_server list info
     */
    form: usecases_PNETServerListInputDTO;
};

export type PostV1PnetServerListResponse = (usecases_PNETServerListResponse);

export type PostV1PnetServerUpsertData = {
    /**
     * pnet_server form info
     */
    form: usecases_PNETServerEditInputDTO;
};

export type PostV1PnetServerUpsertResponse = (usecases_PNETServerEditResponse);

export type PostV1TokenCheckData = {
    /**
     * renew token form info
     */
    form: auth_RenewManagerInputDTO;
};

export type PostV1TokenCheckResponse = (auth_RenewManagerUserResponse);

export type PostV1TokenLoginData = {
    /**
     * credentials form info
     */
    form: auth_RenewManagerCredentialsInputDTO;
};

export type PostV1TokenLoginResponse = (auth_RenewManagerResponse);

export type PostV1TokenLogoutResponse = (auth_RenewManagerResponse);

export type PostV1TokenPasswordChangeData = {
    /**
     * credentials form info
     */
    form: usecases_UserPasswordChangeInputDTO;
};

export type PostV1TokenPasswordChangeResponse = (usecases_UserPasswordRecoverResponse);

export type PostV1TokenRenewData = {
    /**
     * renew token form info
     */
    form: auth_RenewManagerInputDTO;
};

export type PostV1TokenRenewResponse = (auth_RenewManagerResponse);

export type PostV1UserGetData = {
    /**
     * user id
     */
    form: usecases_UserGetInputDTO;
};

export type PostV1UserGetResponse = (usecases_UserGetResponse);

export type PostV1UserListData = {
    /**
     * user list info
     */
    form: usecases_UserListInputDTO;
};

export type PostV1UserListResponse = (usecases_UserListResponse);

export type PostV1UserUpsertData = {
    /**
     * user form info
     */
    form: usecases_UserEditInputDTO;
};

export type PostV1UserUpsertResponse = (usecases_UserEditResponse);

export type GetV2LtiLoginResponse = (unknown);

export type PostV2LtiLoginResponse = (unknown);