// This file is auto-generated by @hey-api/openapi-ts

export type auth_RenewManagerCredentialsInputDTO = {
  email?: string;
  password?: string;
};

export type auth_RenewManagerInputDTO = {
  refresh_token?: string;
};

export type auth_SSOAuthorizeInputDTO = {
  client_id?: string;
  extra?: string;
  path?: string;
  redirect_uri?: string;
  response_type?: string;
  scope?: string;
  state?: string;
  user_id?: number;
};

export type auth_SSOAuthorizeOutputDTO = {
  application?: string;
  code?: string;
  extra?: string;
  path?: string;
  redirect_uri?: string;
  state?: string;
};

export type auth_SSOAuthorizeResponse = {
  error: boolean;
  msg: string;
  result?: auth_SSOAuthorizeOutputDTO;
};

export type auth_SSOError = {
  error?: string;
  error_description?: string;
};

export type auth_SSOTokenIntrospect = {
  active?: boolean;
  client_id?: string;
  exp?: number;
  iat?: number;
  scope?: Array<string>;
  sub?: string;
  token_type?: string;
  username?: string;
};

export type auth_SwaggerSSOToken = {
  access_token?: string;
  expires_in?: number;
  refresh_token?: string;
  state?: string;
  token_type?: string;
  user_id?: number;
};

export type auth_SwaggerSSOTokenPublicData = {
  /**
   * Aud. Получатель токена (обычно client_id приложения, запрашивающего токен)
   */
  aud?: string;
  /**
   * Email. Почта уникальная пользователя
   */
  email?: string;
  /**
   * Exp. Время истечения срока действия токена (в Unix timestamp)
   */
  exp?: number;
  /**
   * Iat. Время выдачи токена (в Unix timestamp)
   */
  iat?: number;
  /**
   * Iss. Идентификатор эмитента токена
   */
  iss?: string;
  /**
   * LastLaunchId. ID пользователя SSO через LMS систему
   */
  last_launch_id?: string;
  /**
   * Name. Полное ФИО пользователя
   */
  name?: string;
  /**
   * Nonce.(Если запрос авторизации включал nonce) Случайное значение для предотвращения атак подмены
   */
  nonce?: string;
  /**
   * Role. Роль пользователя
   */
  role?: string;
  /**
   * ServerID ID сервера аутентификации (как с Iss)
   */
  server_id?: number;
  /**
   * Sub. Уникальный идентификатор пользователя в системе OpenID Provider (OP)
   */
  sub?: number;
};

export type auth_SwaggerSSOTokenResponse = {
  error: boolean;
  msg: string;
  result?: auth_SwaggerSSOToken;
};

export type auth_UserPasswordChangeInputDTO = {
  again_password?: string;
  new_password?: string;
  old_password?: string;
};

export type auth_UserPasswordChangeOutputDTO = {
  id?: number;
};

export type auth_UserPasswordRecoverResponse = {
  error: boolean;
  msg: string;
  result?: auth_UserPasswordChangeOutputDTO;
};

export type external_AttemptDTO = {
  attempt_id: string;
  user_email?: string;
  user_id?: number;
};

export type external_PNETServerPingInputDTO = {
  attempts?: Array<external_AttemptDTO>;
};

export type external_PNETServerPingOutputDTO = {
  count?: number;
};

export type external_PNETServerPingResponse = {
  error: boolean;
  msg: string;
  result?: external_PNETServerPingOutputDTO;
};

export type external_UNLFileSyncInputDTO = {
  branch?: string;
  repository?: string;
};

export type external_UNLFileSyncOutputDTO = {
  count?: number;
};

export type external_UNLFileSyncResponse = {
  error: boolean;
  msg: string;
  result?: external_UNLFileSyncOutputDTO;
};

export type models_LTIAttempt = {
  attempt_id: string;
  created_at: string;
  expired_at: string;
  id?: number;
  lti_routing_id?: number;
  pnet_server_id?: number;
  room_id?: number;
  updated_at: string;
  user_id?: number;
};

export type models_LTIAttemptListItem = {
  attempt_id: string;
  created_at: string;
  expired_at: string;
  id?: number;
  lti_routing_id?: number;
  lti_routing_name?: string;
  pnet_server_id?: number;
  pnet_server_name?: string;
  updated_at: string;
  user_email?: string;
  user_id?: number;
  user_name?: string;
};

export type models_LTIForm = {
  base_uri: string;
  created_at: string;
  id?: number;
  key_set_uri: string;
  lti_auth_login_uri: string;
  lti_auth_token_uri: string;
  lti_client_id: string;
  lti_deployment_id: string;
  name: string;
  private_key: string;
  public_key: string;
  target_link_uri: string;
  updated_at: string;
};

export type models_LTIFormListItem = {
  created_at: string;
  id?: number;
  lti_client_id: string;
  lti_deployment_id: string;
  name: string;
  updated_at: string;
};

export type models_LTIRouting = {
  /**
   * Параметры
   */
  collaboration?: number;
  created_at: string;
  id?: number;
  is_default?: boolean;
  lti_course_id?: string;
  lti_description?: string;
  lti_params_task?: string;
  lti_sub_id?: string;
  /**
   * Автоматические
   */
  lti_task_id?: string;
  /**
   * LTI Params
   */
  lti_title?: string;
  name?: string;
  pinned_session_minutes?: number;
  pnet_labs_path?: string;
  /**
   * The type of PNETLabsType, cms_client.PNETLabsTypeDefault
   * enum: default,enumeration
   */
  pnet_labs_type?: string;
  pnet_server_id?: number;
  pnet_test_path?: string;
  updated_at: string;
};

export type models_LTIRoutingListItem = {
  created_at: string;
  id?: number;
  name?: string;
  updated_at: string;
};

export type models_PNETServer = {
  client_id?: string;
  created_at: string;
  id?: number;
  is_active?: boolean;
  last_count_users?: number;
  last_online_status?: string;
  max_count_users_limit?: number;
  minutes_for_disconnect?: number;
  name?: string;
  token?: string;
  /**
   * enumeration: ServerTypePnet, ServerTypeOpenID
   */
  type?: string;
  unit_rate?: number;
  updated_at: string;
  url?: string;
};

export type models_PNETServerListItem = {
  created_at: string;
  id?: number;
  is_active?: boolean;
  last_count_users?: number;
  last_online_status?: string;
  max_count_users_limit?: number;
  minutes_for_disconnect?: number;
  name?: string;
  /**
   * enumeration: ServerTypePnet, ServerTypeOpenID
   */
  type?: string;
  unit_rate?: number;
  updated_at: string;
  url?: string;
};

export type models_ServiceCard = {
  created_at: string;
  description: string;
  id?: number;
  image_url: string;
  is_active?: boolean;
  name: string;
  order?: number;
  updated_at: string;
  url: string;
};

export type models_ServiceCardListItem = {
  created_at: string;
  description: string;
  id?: number;
  image_url: string;
  is_active?: boolean;
  name: string;
  order?: number;
  updated_at: string;
  url: string;
};

export type models_UNLFile = {
  /**
   * Содержимое файла
   */
  content?: Array<number>;
  created_at: string;
  deleted_at?: string;
  id?: number;
  path: string;
  synced_id?: string;
  type?: string;
  updated_at: string;
};

export type models_UNLFileListItem = {
  created_at: string;
  deleted_at?: string;
  id?: number;
  path: string;
  type?: string;
  updated_at: string;
};

export type models_User = {
  created_at: string;
  deleted_at?: string;
  email?: string;
  group_name: string;
  id?: number;
  last_launch_id?: string;
  lti_user_id?: string;
  name?: string;
  updated_at: string;
  user_role: string;
};

export type models_UserListItem = {
  created_at: string;
  deleted_at?: string;
  email?: string;
  group_name: string;
  id?: number;
  lti_user_id?: string;
  name?: string;
  updated_at: string;
  user_role: string;
};

export type queries_RoundQueuePoolPnetListItem = {
  connected_at: string;
  id?: number;
  last_used: boolean;
  name?: string;
  type: string;
};

export type round_queue_pool_pnet_RoundQueuePoolPnetListOutputDTO = {
  model: Array<queries_RoundQueuePoolPnetListItem>;
};

export type round_queue_pool_pnet_RoundQueuePoolPnetListResponse = {
  error: boolean;
  msg: string;
  result?: round_queue_pool_pnet_RoundQueuePoolPnetListOutputDTO;
};

export type round_queue_pool_pnet_RoundQueuePoolPnetUpsertOutputDTO = unknown;

export type round_queue_pool_pnet_RoundQueuePoolPnetUpsertResponse = {
  error: boolean;
  msg: string;
  result?: round_queue_pool_pnet_RoundQueuePoolPnetUpsertOutputDTO;
};

export type usecases_LTIAttemptCreateInputDTO = {
  room_number?: number;
};

export type usecases_LTIAttemptCreateOutputDTO = {
  auto_redirect?: boolean;
  collaboration?: number;
  members?: Array<models_UserListItem>;
  next_url?: string;
  room_number?: number;
};

export type usecases_LTIAttemptCreateResponse = {
  error: boolean;
  msg: string;
  result?: usecases_LTIAttemptCreateOutputDTO;
};

export type usecases_LTIAttemptDeleteInputDTO = {
  id?: number;
};

export type usecases_LTIAttemptDeleteResponse = {
  error: boolean;
  msg: string;
  result?: usecases_LTIAttemptDeleteInputDTO;
};

export type usecases_LTIAttemptEditInputDTO = {
  expired_at: string;
  id?: number;
  pnet_server_id?: number;
};

export type usecases_LTIAttemptEditOutputDTO = {
  id?: number;
};

export type usecases_LTIAttemptEditResponse = {
  error: boolean;
  msg: string;
  result?: usecases_LTIAttemptEditOutputDTO;
};

export type usecases_LTIAttemptGetInputDTO = {
  id?: number;
};

export type usecases_LTIAttemptGetOutputDTO = {
  model?: models_LTIAttempt;
};

export type usecases_LTIAttemptGetResponse = {
  error: boolean;
  msg: string;
  result?: usecases_LTIAttemptGetOutputDTO;
};

export type usecases_LTIAttemptListInputDTO = {
  limit?: number;
  offset?: number;
  user_ids?: Array<number>;
};

export type usecases_LTIAttemptListOutputDTO = {
  model: Array<models_LTIAttemptListItem>;
};

export type usecases_LTIAttemptListResponse = {
  error: boolean;
  msg: string;
  result?: usecases_LTIAttemptListOutputDTO;
};

export type usecases_LTIFormDeleteInputDTO = {
  id?: number;
};

export type usecases_LTIFormDeleteResponse = {
  error: boolean;
  msg: string;
  result?: usecases_LTIFormDeleteInputDTO;
};

export type usecases_LTIFormEditInputDTO = {
  auth_login_uri: string;
  auth_token_uri: string;
  base_uri: string;
  client_id: string;
  deployment_id: string;
  id?: number;
  key_set_uri: string;
  name: string;
  target_link_uri: string;
};

export type usecases_LTIFormEditOutputDTO = {
  id?: number;
};

export type usecases_LTIFormEditResponse = {
  error: boolean;
  msg: string;
  result?: usecases_LTIFormEditOutputDTO;
};

export type usecases_LTIFormGetInputDTO = {
  id?: number;
};

export type usecases_LTIFormGetOutputDTO = {
  model?: models_LTIForm;
};

export type usecases_LTIFormGetResponse = {
  error: boolean;
  msg: string;
  result?: usecases_LTIFormGetOutputDTO;
};

export type usecases_LTIFormListInputDTO = {
  limit?: number;
  offset?: number;
  search?: string;
};

export type usecases_LTIFormListOutputDTO = {
  model: Array<models_LTIFormListItem>;
  total_count: number;
};

export type usecases_LTIFormListResponse = {
  error: boolean;
  msg: string;
  result?: usecases_LTIFormListOutputDTO;
};

export type usecases_LTIRoutingDeleteInputDTO = {
  id?: number;
};

export type usecases_LTIRoutingDeleteResponse = {
  error: boolean;
  msg: string;
  result?: usecases_LTIRoutingDeleteInputDTO;
};

export type usecases_LTIRoutingEditInputDTO = {
  collaboration?: number;
  id?: number;
  is_default?: boolean;
  lti_course_id?: string;
  lti_description?: string;
  lti_params_task?: string;
  lti_sub_id?: string;
  lti_task_id?: string;
  lti_title?: string;
  name?: string;
  pinned_session_minutes?: number;
  pnet_labs_path?: string;
  pnet_labs_type?: string;
  pnet_server_id?: number;
  pnet_test_path?: string;
};

export type usecases_LTIRoutingEditOutputDTO = {
  id?: number;
};

export type usecases_LTIRoutingEditResponse = {
  error: boolean;
  msg: string;
  result?: usecases_LTIRoutingEditOutputDTO;
};

export type usecases_LTIRoutingGetInputDTO = {
  id?: number;
};

export type usecases_LTIRoutingGetOutputDTO = {
  model?: models_LTIRouting;
};

export type usecases_LTIRoutingGetResponse = {
  error: boolean;
  msg: string;
  result?: usecases_LTIRoutingGetOutputDTO;
};

export type usecases_LTIRoutingListInputDTO = {
  limit?: number;
  offset?: number;
  search?: string;
};

export type usecases_LTIRoutingListOutputDTO = {
  model: Array<models_LTIRoutingListItem>;
  total_count: number;
};

export type usecases_LTIRoutingListResponse = {
  error: boolean;
  msg: string;
  result?: usecases_LTIRoutingListOutputDTO;
};

export type usecases_PNETServerDeleteInputDTO = {
  id?: number;
};

export type usecases_PNETServerDeleteResponse = {
  error: boolean;
  msg: string;
  result?: usecases_PNETServerDeleteInputDTO;
};

export type usecases_PNETServerEditInputDTO = {
  client_id?: string;
  id?: number;
  is_active?: boolean;
  max_count_users_limit?: number;
  minutes_for_disconnect?: number;
  name: string;
  type: string;
  unit_rate?: number;
  url: string;
};

export type usecases_PNETServerEditOutputDTO = {
  id?: number;
};

export type usecases_PNETServerEditResponse = {
  error: boolean;
  msg: string;
  result?: usecases_PNETServerEditOutputDTO;
};

export type usecases_PNETServerGetInputDTO = {
  id?: number;
};

export type usecases_PNETServerGetOutputDTO = {
  model?: models_PNETServer;
};

export type usecases_PNETServerGetResponse = {
  error: boolean;
  msg: string;
  result?: usecases_PNETServerGetOutputDTO;
};

export type usecases_PNETServerListInputDTO = {
  limit?: number;
  offset?: number;
  /**
   * The type of orderBy
   * enum: createdAt,unitRate,lastCountUsers
   */
  order_by?: string;
  search?: string;
  /**
   * The type of status
   * enum: all,active
   */
  status?: string;
  types?: Array<string>;
};

export type usecases_PNETServerListOutputDTO = {
  model: Array<models_PNETServerListItem>;
  total_count: number;
};

export type usecases_PNETServerListResponse = {
  error: boolean;
  msg: string;
  result?: usecases_PNETServerListOutputDTO;
};

export type usecases_ServiceCardDeleteInputDTO = {
  id?: number;
};

export type usecases_ServiceCardDeleteResponse = {
  error: boolean;
  msg: string;
  result?: usecases_ServiceCardDeleteInputDTO;
};

export type usecases_ServiceCardEditInputDTO = {
  description?: string;
  id?: number;
  image_url?: string;
  is_active?: boolean;
  name?: string;
  order?: number;
  url?: string;
};

export type usecases_ServiceCardEditOutputDTO = {
  id?: number;
};

export type usecases_ServiceCardEditResponse = {
  error: boolean;
  msg: string;
  result?: usecases_ServiceCardEditOutputDTO;
};

export type usecases_ServiceCardGetInputDTO = {
  id?: number;
};

export type usecases_ServiceCardGetOutputDTO = {
  model?: models_ServiceCard;
};

export type usecases_ServiceCardGetResponse = {
  error: boolean;
  msg: string;
  result?: usecases_ServiceCardGetOutputDTO;
};

export type usecases_ServiceCardListInputDTO = {
  limit?: number;
  offset?: number;
  search?: string;
};

export type usecases_ServiceCardListOutputDTO = {
  model: Array<models_ServiceCardListItem>;
  total_count: number;
};

export type usecases_ServiceCardListResponse = {
  error: boolean;
  msg: string;
  result?: usecases_ServiceCardListOutputDTO;
};

export type usecases_UNLFileGetInputDTO = {
  id?: number;
};

export type usecases_UNLFileGetOutputDTO = {
  model?: models_UNLFile;
};

export type usecases_UNLFileGetResponse = {
  error: boolean;
  msg: string;
  result?: usecases_UNLFileGetOutputDTO;
};

export type usecases_UNLFileListInputDTO = {
  limit?: number;
  offset?: number;
  search?: string;
  type?: Array<string>;
};

export type usecases_UNLFileListOutputDTO = {
  model: Array<models_UNLFileListItem>;
};

export type usecases_UNLFileListResponse = {
  error: boolean;
  msg: string;
  result?: usecases_UNLFileListOutputDTO;
};

export type usecases_UserEditInputDTO = {
  email: string;
  group_name?: string;
  id?: number;
  is_active?: boolean;
  lti_user_id?: string;
  name: string;
  user_role?: string;
};

export type usecases_UserEditOutputDTO = {
  id?: number;
};

export type usecases_UserEditResponse = {
  error: boolean;
  msg: string;
  result?: usecases_UserEditOutputDTO;
};

export type usecases_UserGetInputDTO = {
  id?: number;
};

export type usecases_UserGetOutputDTO = {
  model?: models_User;
};

export type usecases_UserGetResponse = {
  error: boolean;
  msg: string;
  result?: usecases_UserGetOutputDTO;
};

export type usecases_UserListInputDTO = {
  limit?: number;
  offset?: number;
  search?: string;
  user_ids?: Array<number>;
};

export type usecases_UserListOutputDTO = {
  model: Array<models_UserListItem>;
  total_count: number;
};

export type usecases_UserListResponse = {
  error: boolean;
  msg: string;
  result?: usecases_UserListOutputDTO;
};

export type PostV1LtiAttemptCreateData = {
  /**
   * lti_attempt form info
   */
  form: usecases_LTIAttemptCreateInputDTO;
};

export type PostV1LtiAttemptCreateResponse = usecases_LTIAttemptCreateResponse;

export type PostV1LtiAttemptDeleteData = {
  /**
   * lti_attempt id
   */
  form: usecases_LTIAttemptDeleteInputDTO;
};

export type PostV1LtiAttemptDeleteResponse = usecases_LTIAttemptDeleteResponse;

export type PostV1LtiAttemptEditData = {
  /**
   * lti_attempt form info
   */
  form: usecases_LTIAttemptEditInputDTO;
};

export type PostV1LtiAttemptEditResponse = usecases_LTIAttemptEditResponse;

export type PostV1LtiAttemptGetData = {
  /**
   * lti_attempt id
   */
  form: usecases_LTIAttemptGetInputDTO;
};

export type PostV1LtiAttemptGetResponse = usecases_LTIAttemptGetResponse;

export type PostV1LtiAttemptListData = {
  /**
   * lti_attempt list info
   */
  form: usecases_LTIAttemptListInputDTO;
};

export type PostV1LtiAttemptListResponse = usecases_LTIAttemptListResponse;

export type PostV1LtiFormDeleteData = {
  /**
   * lti_form id
   */
  form: usecases_LTIFormDeleteInputDTO;
};

export type PostV1LtiFormDeleteResponse = usecases_LTIFormDeleteResponse;

export type PostV1LtiFormGetData = {
  /**
   * lti_form id
   */
  form: usecases_LTIFormGetInputDTO;
};

export type PostV1LtiFormGetResponse = usecases_LTIFormGetResponse;

export type PostV1LtiFormListData = {
  /**
   * lti_form list info
   */
  form: usecases_LTIFormListInputDTO;
};

export type PostV1LtiFormListResponse = usecases_LTIFormListResponse;

export type PostV1LtiFormUpsertData = {
  /**
   * lti_form form info
   */
  form: usecases_LTIFormEditInputDTO;
};

export type PostV1LtiFormUpsertResponse = usecases_LTIFormEditResponse;

export type PostV1LtiRoutingDeleteData = {
  /**
   * lti_routing id
   */
  form: usecases_LTIRoutingDeleteInputDTO;
};

export type PostV1LtiRoutingDeleteResponse = usecases_LTIRoutingDeleteResponse;

export type PostV1LtiRoutingGetData = {
  /**
   * lti_routing id
   */
  form: usecases_LTIRoutingGetInputDTO;
};

export type PostV1LtiRoutingGetResponse = usecases_LTIRoutingGetResponse;

export type PostV1LtiRoutingListData = {
  /**
   * lti_routing list info
   */
  form: usecases_LTIRoutingListInputDTO;
};

export type PostV1LtiRoutingListResponse = usecases_LTIRoutingListResponse;

export type PostV1LtiRoutingUpsertData = {
  /**
   * lti_routing form info
   */
  form: usecases_LTIRoutingEditInputDTO;
};

export type PostV1LtiRoutingUpsertResponse = usecases_LTIRoutingEditResponse;

export type PostV1PnetServerQueueListResponse = round_queue_pool_pnet_RoundQueuePoolPnetListResponse;

export type PostV1PnetServerQueueUpsertResponse = round_queue_pool_pnet_RoundQueuePoolPnetUpsertResponse;

export type PostV1PnetServerDeleteData = {
  /**
   * pnet_server id
   */
  form: usecases_PNETServerDeleteInputDTO;
};

export type PostV1PnetServerDeleteResponse = usecases_PNETServerDeleteResponse;

export type PostV1PnetServerGetData = {
  /**
   * pnet_server id
   */
  form: usecases_PNETServerGetInputDTO;
};

export type PostV1PnetServerGetResponse = usecases_PNETServerGetResponse;

export type PostV1PnetServerListData = {
  /**
   * pnet_server list info
   */
  form: usecases_PNETServerListInputDTO;
};

export type PostV1PnetServerListResponse = usecases_PNETServerListResponse;

export type PostV1PnetServerPingData = {
  /**
   * Basic-токен, созданный клиентом
   */
  authorization: string;
  /**
   * pnet_server id
   */
  form: external_PNETServerPingInputDTO;
};

export type PostV1PnetServerPingResponse = external_PNETServerPingResponse;

export type PostV1PnetServerUpsertData = {
  /**
   * pnet_server form info
   */
  form: usecases_PNETServerEditInputDTO;
};

export type PostV1PnetServerUpsertResponse = usecases_PNETServerEditResponse;

export type PostV1ServiceCardDeleteData = {
  /**
   * service_card id
   */
  form: usecases_ServiceCardDeleteInputDTO;
};

export type PostV1ServiceCardDeleteResponse = usecases_ServiceCardDeleteResponse;

export type PostV1ServiceCardGetData = {
  /**
   * service_card id
   */
  form: usecases_ServiceCardGetInputDTO;
};

export type PostV1ServiceCardGetResponse = usecases_ServiceCardGetResponse;

export type PostV1ServiceCardListData = {
  /**
   * service_card list info
   */
  form: usecases_ServiceCardListInputDTO;
};

export type PostV1ServiceCardListResponse = usecases_ServiceCardListResponse;

export type PostV1ServiceCardUpsertData = {
  /**
   * service_card form info
   */
  form: usecases_ServiceCardEditInputDTO;
};

export type PostV1ServiceCardUpsertResponse = usecases_ServiceCardEditResponse;

export type GetV1SsoWellKnownOpenidConfigurationResponse = auth_SSOAuthorizeResponse;

export type GetV1SsoAuthorizeData = {
  /**
   * Код приложения клиента
   */
  clientId: string;
  /**
   * Дополнительные параметры вида base64
   */
  extra?: string;
  /**
   * Путь, возвращается в параметрах редиректа
   */
  path?: string;
  /**
   * Адрес переадресации клиента
   */
  redirectUri: string;
  /**
   * Тип ответа. Возможные значения: [code]
   */
  responseType: 'code';
  /**
   * Область доступа (значения, разделённые запятой). Возможные значения: [default, openid]
   */
  scope: 'default' | 'openid';
  /**
   * Состояние, возвращается в параметрах редиректа, участвует в генерации кода авторизации
   */
  state?: string;
};

export type GetV1SsoAuthorizeResponse = auth_SSOAuthorizeResponse;

export type PostV1SsoAuthorizeData = {
  /**
   * renew token form info
   */
  form: auth_SSOAuthorizeInputDTO;
};

export type PostV1SsoAuthorizeResponse = auth_SSOAuthorizeResponse;

export type PostV1SsoIntrospectData = {
  /**
   * Basic-токен, созданный клиентом
   */
  authorization: string;
  /**
   * Токен доступа или токен обновления
   */
  token: string;
};

export type PostV1SsoIntrospectResponse = auth_SSOTokenIntrospect;

export type PostV1SsoTokenData = {
  /**
   * Basic-токен, созданный клиентом
   */
  authorization: string;
  /**
   * Код авторизации
   */
  code?: string;
  /**
   * Тип авторизации [authorization_code, refresh_token]
   */
  grantType: 'authorization_code' | 'refresh_token';
  /**
   * Адрес переадресации клиента
   */
  redirectUri?: string;
  /**
   * Токен обновления
   */
  refreshToken?: string;
};

export type PostV1SsoTokenResponse = auth_SwaggerSSOToken;

export type GetV1SsoUserinfoData = {
  /**
   * Bearer токен
   */
  authorization: string;
};

export type GetV1SsoUserinfoResponse = auth_SwaggerSSOTokenPublicData;

export type PostV1TokenLoginData = {
  /**
   * credentials form info
   */
  form: auth_RenewManagerCredentialsInputDTO;
};

export type PostV1TokenLoginResponse = auth_SwaggerSSOTokenResponse;

export type PostV1TokenLogoutResponse = auth_SwaggerSSOTokenResponse;

export type PostV1TokenPasswordChangeData = {
  /**
   * credentials form info
   */
  form: auth_UserPasswordChangeInputDTO;
};

export type PostV1TokenPasswordChangeResponse = auth_UserPasswordRecoverResponse;

export type PostV1TokenRenewData = {
  /**
   * renew token form info
   */
  form: auth_RenewManagerInputDTO;
};

export type PostV1TokenRenewResponse = auth_SwaggerSSOTokenResponse;

export type PostV1UnlFileGetData = {
  /**
   * unl_file id
   */
  form: usecases_UNLFileGetInputDTO;
};

export type PostV1UnlFileGetResponse = usecases_UNLFileGetResponse;

export type PostV1UnlFileListData = {
  /**
   * unl_file list info
   */
  form: usecases_UNLFileListInputDTO;
};

export type PostV1UnlFileListResponse = usecases_UNLFileListResponse;

export type PostV1UnlFileSyncData = {
  /**
   * Basic-токен, созданный клиентом
   */
  authorization: string;
  /**
   * sync params
   */
  form: external_UNLFileSyncInputDTO;
};

export type PostV1UnlFileSyncResponse = external_UNLFileSyncResponse;

export type PostV1UserGetData = {
  /**
   * user id
   */
  form: usecases_UserGetInputDTO;
};

export type PostV1UserGetResponse = usecases_UserGetResponse;

export type PostV1UserListData = {
  /**
   * user list info
   */
  form: usecases_UserListInputDTO;
};

export type PostV1UserListResponse = usecases_UserListResponse;

export type PostV1UserUpsertData = {
  /**
   * user form info
   */
  form: usecases_UserEditInputDTO;
};

export type PostV1UserUpsertResponse = usecases_UserEditResponse;

export type GetV2LtiLoginResponse = unknown;

export type PostV2LtiLoginResponse = unknown;
