#!/bin/bash

# Создание .env файла, если его нет
if [ ! -f /etc/pnetlabaddon/.env ]; then
    cp /etc/pnetlabaddon/.env.test /etc/pnetlabaddon/.env
fi

# Миграция базы данных
cd /etc/pnetlabaddon && /etc/pnetlabaddon/migrate.sh up && cd -

# Инъецирование front-end и распаковка views
PNETDIR=/opt/unetlab
VIEWS=$PNETDIR/html/store/resources/views/pnetapiviews
rm -rf resources
mkdir -p /etc/pnetlabaddon/resources/view $VIEWS
unzip /etc/pnetlabaddon/pnetlab-inject.zip -d /etc/pnetlabaddon/resources/views
sudo cp -Rf /etc/pnetlabaddon/resources/views/pnetlab-inject/main.blade.php $VIEWS
sudo cp -Rf /etc/pnetlabaddon/resources/views/pnetlab-inject/pnetlabapijs $PNETDIR/html/store/public/main/js
EXTENSION_JS=$(cat /etc/pnetlabaddon/resources/views/pnetlab-inject/pnetlabapijs.html)
LAB_PAGE_FILE=$PNETDIR/html/themes/default/index.html
if ! grep -q "$EXTENSION_JS" $LAB_PAGE_FILE; then
  echo $EXTENSION_JS >>$LAB_PAGE_FILE
fi
sudo chown -R www-data:www-data $VIEWS/*

# Перезагрузка systemd и запуск сервиса
systemctl daemon-reload
systemctl enable pnetlabaddon
systemctl start pnetlabaddon
