FROM golang:alpine3.21

WORKDIR /app

RUN go install golang.org/x/pkgsite/cmd/pkgsite@latest

COPY . /app

# Command to run when starting the container.
CMD ["pkgsite", "-http", "0.0.0.0:8080", "-open", "."]
EXPOSE 8080
