package usecases

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"time"

	"gitlab.com/a10869/api-modules/shared/guacamole_client"

	"github.com/rs/zerolog"

	"github.com/google/uuid"
	"gitlab.com/a10869/api-modules/pnetlabaddon/app/models"
	"gitlab.com/a10869/api-modules/pnetlabaddon/app/queries"
	"gitlab.com/a10869/api-modules/shared/cms_client"
)

type SSOSecondFactorInputDTO struct {
	Code        string `json:"code"`
	Application string `json:"application"`
	Path        string `json:"path"`
	State       string `json:"state"`
	Extra       string `json:"extra"`
	RedirectURI string `json:"redirect_uri"`
}

type SSOSecondFactorUC struct {
	CMSClient        *cms_client.CMSClient
	UserQueries      *queries.UserQueries
	UserRoleQueries  *queries.UserRoleQueries
	GuacamoleQueries *queries.GuacamoleQueries
	GuacamoleClient  *guacamole_client.GuacamoleClient
	*zerolog.Logger
}

type SSOSecondFactorOutputDTO struct {
	CookieToken        string    `json:"cookie_token"`
	CookieAge          time.Time `json:"cookie_age"`
	CookieMaxAge       int       `json:"cookie_max_age"`
	RefreshToken       string    `json:"refresh_token"`
	RefreshTokenAge    time.Time `json:"refresh_token_age"`
	RefreshTokenMaxAge int       `json:"refresh_max_age"`
}

func (u *SSOSecondFactorUC) passwordToSHA256(password string) string {
	h := sha256.New()
	h.Write([]byte(password))
	bs := h.Sum(nil)
	return hex.EncodeToString(bs)
}

func (u *SSOSecondFactorUC) Execute(dto SSOSecondFactorInputDTO) (*SSOSecondFactorOutputDTO, error) {
	u.Logger.Info().Msg(
		fmt.Sprintf(
			"Second factor state=%s, application=%s, redirect=%s", dto.State, dto.Application, dto.RedirectURI,
		),
	)
	if u.CMSClient.Config.ClientID != dto.Application {
		return nil, errors.New("invalid application")
	}
	token, err := u.CMSClient.SSOToken(
		"authorization_code",
		dto.RedirectURI,
		dto.Code,
		"",
	)
	if err != nil {
		return nil, err
	}
	u.Logger.Info().Msg(
		fmt.Sprintf(
			"Get token by OTP code user_id=%d, state=%s", token.UserId, token.State,
		),
	)
	if dto.State != token.State {
		return nil, errors.New("invalid state")
	}
	user, err := u.CMSClient.SSOUserInfo(token.AccessToken)
	if err != nil {
		return nil, err
	}
	u.Logger.Info().Msg(
		fmt.Sprintf(
			"Get user by access token user_id=%d, email=%s", user.Id, user.Email,
		),
	)
	if user.Email == "" {
		return nil, errors.New("invalid user email")
	}
	roleDB, err := u.UserRoleQueries.GetOrCreateDefault()
	if err != nil {
		return nil, err
	}
	u.Logger.Info().Msg(
		fmt.Sprintf(
			"Get or create role role_id=%d, role_name=%s", roleDB.UserRoleID, roleDB.UserRoleName,
		),
	)
	userDB, err := u.UserQueries.GetOrCreateByEmail(models.User{
		Username:   user.Name,
		Email:      user.Email,
		Expiration: -1,
		Password:   uuid.New().String(),
		Role:       fmt.Sprintf("%d", roleDB.UserRoleID),
		HTML5:      true,
		UserStatus: 1,
	})
	if err != nil {
		u.Logger.Info().Msg(
			fmt.Sprintf(
				"Get or create user user_id=%d, email=%s with error=%+v", user.Id, user.Email, err,
			),
		)
		return nil, err
	}
	u.Logger.Info().Msg(
		fmt.Sprintf(
			"Get or create user user_id=%d, email=%s user_pod=%d", user.Id, user.Email, userDB.Pod,
		),
	)
	userDB.Name = fmt.Sprintf("%d", user.Id)
	session := time.Now().Add(2 * time.Hour).Unix()
	userDB.Session = &session
	userDB.Cookie = uuid.New().String()
	userDB.Password = u.passwordToSHA256(uuid.New().String())
	userDB.OnlineTime = time.Now().Unix()
	offline := 1
	userDB.Offline = &offline
	result := u.UserQueries.Save(&userDB)
	if result.Error != nil {
		return nil, result.Error
	}
	u.Logger.Info().Msg(
		fmt.Sprintf(
			"Response cookies generated by user_id=%d, email=%s", user.Id, user.Email,
		),
	)
	//
	// Создание пользователя Guacamole
	//
	err = u.GuacamoleQueries.UserReplace(
		userDB.Pod,
		userDB.Email,
		userDB.Password,
	)
	if err != nil {
		return nil, err
	}
	guacamoleToken, err := u.GuacamoleClient.GetToken(
		userDB.Email,
		userDB.Password,
	)
	if err != nil {
		return nil, err
	}
	err = u.GuacamoleQueries.TokenReplace(
		userDB.Pod,
		userDB.Email,
		guacamoleToken.AuthToken,
	)
	if err != nil {
		return nil, err
	}
	return &SSOSecondFactorOutputDTO{
		CookieToken:        userDB.Cookie,
		CookieAge:          time.Now().Add(2 * time.Hour),
		CookieMaxAge:       7200,
		RefreshToken:       token.RefreshToken,
		RefreshTokenAge:    time.Now().Add(12 * time.Hour),
		RefreshTokenMaxAge: 43200,
	}, nil
}
