package usecases

import (
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/rs/zerolog/log"
	"gitlab.com/a10869/api-modules/pnetlabaddon/app/models"
	"gitlab.com/a10869/api-modules/pnetlabaddon/app/queries"
	"gitlab.com/a10869/api-modules/shared/cms_client"
)

type SSOSecondFactorInputDTO struct {
	Code        string `json:"code"`
	Application string `json:"application"`
	Path        string `json:"path"`
	State       string `json:"state"`
	Extra       string `json:"extra"`
	RedirectURI string `json:"redirect_uri"`
}

type SSOSecondFactorUC struct {
	CMSClient       *cms_client.CMSClient
	UserQueries     *queries.UserQueries
	UserRoleQueries *queries.UserRoleQueries
}

type SSOSecondFactorOutputDTO struct {
	CookieToken     string    `json:"cookie_token"`
	CookieAge       time.Time `json:"cookie_age"`
	RefreshToken    string    `json:"refresh_token"`
	RefreshTokenAge time.Time `json:"refresh_token_age"`
}

func (u *SSOSecondFactorUC) Execute(dto SSOSecondFactorInputDTO) (*SSOSecondFactorOutputDTO, error) {
	log.Info().Msg(
		fmt.Sprintf(
			"Second factor state=%s, application=%s, redirect=%s", dto.State, dto.Application, dto.RedirectURI,
		),
	)
	if u.CMSClient.ClintID != dto.Application {
		return nil, errors.New("invalid application")
	}
	token, err := u.CMSClient.SSOToken(
		"authorization_code",
		dto.RedirectURI,
		dto.Code,
		"",
	)
	if err != nil {
		return nil, err
	}
	log.Info().Msg(
		fmt.Sprintf(
			"Get token by OTP code user_id=%d, state=%s", token.UserId, token.State,
		),
	)
	if dto.State != token.State {
		return nil, errors.New("invalid state")
	}
	user, err := u.CMSClient.SSOUserInfo(token.AccessToken)
	if err != nil {
		return nil, err
	}
	log.Info().Msg(
		fmt.Sprintf(
			"Get user by access token user_id=%d, email=%s", user.Id, user.Email,
		),
	)
	if user.Email == "" {
		return nil, errors.New("invalid user email")
	}
	roleDB, err := u.UserRoleQueries.GetOrCreateDefault()
	if err != nil {
		return nil, err
	}
	log.Info().Msg(
		fmt.Sprintf(
			"Get or create role role_id=%d, role_name=%s", roleDB.UserRoleID, roleDB.UserRoleName,
		),
	)
	userDB, err := u.UserQueries.GetOrCreateByEmail(models.User{
		Username:   user.Name,
		Email:      user.Email,
		Expiration: -1,
		Password:   uuid.New().String(),
		Role:       fmt.Sprintf("%d", roleDB.UserRoleID),
		HTML5:      true,
		UserStatus: 1,
	})
	if err != nil {
		log.Info().Msg(
			fmt.Sprintf(
				"Get or create user user_id=%d, email=%s with error=%+v", user.Id, user.Email, err,
			),
		)
		return nil, err
	}
	log.Info().Msg(
		fmt.Sprintf(
			"Get or create user user_id=%d, email=%s user_pod=%d", user.Id, user.Email, userDB.Pod,
		),
	)
	userDB.Name = fmt.Sprintf("%d", user.Id)
	userDB.Cookie = uuid.New().String()
	result := u.UserQueries.Save(&userDB)
	if result.Error != nil {
		return nil, result.Error
	}
	log.Info().Msg(
		fmt.Sprintf(
			"Response cookies generated by user_id=%d, email=%s", user.Id, user.Email,
		),
	)
	return &SSOSecondFactorOutputDTO{
		CookieToken:     userDB.Cookie,
		CookieAge:       time.Now().Add(time.Hour),
		RefreshToken:    token.RefreshToken,
		RefreshTokenAge: time.Now().Add(12 * time.Hour),
	}, nil
}
