// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type {
  PostV1TasksListData,
  PostV1TasksListResponse,
  GetV1TokensJsonResponse,
  GetV1TokensYamlResponse,
  PostV1TopologiesCreateData,
  PostV1TopologiesCreateResponse,
  PostV1TopologiesDeleteData,
  PostV1TopologiesDeleteResponse,
  PostV1TopologiesGetData,
  PostV1TopologiesGetResponse
} from './types.gen';

/**
 * list tasks
 * List tasks. Roles: [admin, instructor]
 * @param data The data for the request.
 * @param data.form tasks list info
 * @returns usecases_TasksListResponse OK
 * @throws ApiError
 */
export const postV1TasksList = (data: PostV1TasksListData): CancelablePromise<PostV1TasksListResponse> => {
  return __request(OpenAPI, {
    method: 'POST',
    url: '/v1/tasks/list',
    body: data.form
  });
};

/**
 * token cluster json
 * Token cluster. Roles: [student, admin, instructor]
 * @returns usecases_TokenAccessGetResponse OK
 * @throws ApiError
 */
export const getV1TokensJson = (): CancelablePromise<GetV1TokensJsonResponse> => {
  return __request(OpenAPI, {
    method: 'GET',
    url: '/v1/tokens/json'
  });
};

/**
 * token cluster yaml
 * Token cluster. Roles: any
 * @returns usecases_TokenFileYAMLGetResponse OK
 * @throws ApiError
 */
export const getV1TokensYaml = (): CancelablePromise<GetV1TokensYamlResponse> => {
  return __request(OpenAPI, {
    method: 'GET',
    url: '/v1/tokens/yaml'
  });
};

/**
 * create personal topologies
 * create personal topology. Roles: [student, admin, instructor]
 * @param data The data for the request.
 * @param data.form create params
 * @returns usecases_TopologiesCreateResponse OK
 * @throws ApiError
 */
export const postV1TopologiesCreate = (
  data: PostV1TopologiesCreateData
): CancelablePromise<PostV1TopologiesCreateResponse> => {
  return __request(OpenAPI, {
    method: 'POST',
    url: '/v1/topologies/create',
    body: data.form
  });
};

/**
 * delete personal topologies
 * delete personal topology. Roles: [student, admin, instructor]
 * @param data The data for the request.
 * @param data.form delete params
 * @returns usecases_TopologiesDeleteResponse OK
 * @throws ApiError
 */
export const postV1TopologiesDelete = (
  data: PostV1TopologiesDeleteData
): CancelablePromise<PostV1TopologiesDeleteResponse> => {
  return __request(OpenAPI, {
    method: 'POST',
    url: '/v1/topologies/delete',
    body: data.form
  });
};

/**
 * list tasks
 * List tasks. Roles: [student, admin, instructor]
 * @param data The data for the request.
 * @param data.form topology namespace
 * @returns usecases_TopologiesGetResponse OK
 * @throws ApiError
 */
export const postV1TopologiesGet = (data: PostV1TopologiesGetData): CancelablePromise<PostV1TopologiesGetResponse> => {
  return __request(OpenAPI, {
    method: 'POST',
    url: '/v1/topologies/get',
    body: data.form
  });
};
