// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { PostV1TasksListData, PostV1TasksListResponse, PostV1TopologiesGetData, PostV1TopologiesGetResponse } from './types.gen';

/**
 * list tasks
 * List tasks. Roles: [admin, instructor]
 * @param data The data for the request.
 * @param data.form tasks list info
 * @returns usecases_TasksListResponse OK
 * @throws ApiError
 */
export const postV1TasksList = (data: PostV1TasksListData): CancelablePromise<PostV1TasksListResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/v1/tasks/list',
        body: data.form
    });
};

/**
 * list tasks
 * List tasks. Roles: [student, admin, instructor]
 * @param data The data for the request.
 * @param data.form topology namespace
 * @returns usecases_TopologiesGetResponse OK
 * @throws ApiError
 */
export const postV1TopologiesGet = (data: PostV1TopologiesGetData): CancelablePromise<PostV1TopologiesGetResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/v1/topologies/get',
        body: data.form
    });
};