// This file is auto-generated by @hey-api/openapi-ts

export type queries_TaskCodeRegistryItem = {
    full_path?: string;
    id?: string;
    title?: string;
};

export type topology_TopologiesEdge = {
    data?: topology_TopologiesEdgeData;
    id?: string;
    source?: string;
    target?: string;
    type?: string;
};

export type topology_TopologiesEdgeData = {
    source?: topology_TopologiesEdgeDataItem;
    target?: topology_TopologiesEdgeDataItem;
};

export type topology_TopologiesEdgeDataItem = {
    id?: string;
    label?: string;
    name?: string;
    type?: string;
};

export type topology_TopologiesNode = {
    /**
     * Icon enum:cloud,router,server,switch,desktop
     */
    icon?: string;
    id?: string;
    label?: string;
    type?: string;
};

export type topology_Topology = {
    direction?: string;
    edges?: Array<topology_TopologiesEdge>;
    nodes?: Array<topology_TopologiesNode>;
};

export type usecases_TasksListInputDTO = unknown;

export type usecases_TasksListOutputDTO = {
    model: Array<queries_TaskCodeRegistryItem>;
};

export type usecases_TasksListResponse = {
    error: boolean;
    msg: string;
    result?: usecases_TasksListOutputDTO;
};

export type usecases_TopologiesGetInputDTO = {
    namespace?: string;
};

export type usecases_TopologiesGetOutputDTO = {
    topology?: topology_Topology;
};

export type usecases_TopologiesGetResponse = {
    error: boolean;
    msg: string;
    result?: usecases_TopologiesGetOutputDTO;
};

export type PostV1TasksListData = {
    /**
     * tasks list info
     */
    form: usecases_TasksListInputDTO;
};

export type PostV1TasksListResponse = (usecases_TasksListResponse);

export type PostV1TopologiesGetData = {
    /**
     * topology namespace
     */
    form: usecases_TopologiesGetInputDTO;
};

export type PostV1TopologiesGetResponse = (usecases_TopologiesGetResponse);