// This file is auto-generated by @hey-api/openapi-ts

export type queries_TaskCodeRegistryItem = {
  full_path?: string;
  id?: string;
  namespace_suffix?: string;
  title?: string;
};

export type topology_TopologiesEdge = {
  data?: topology_TopologiesEdgeData;
  id?: string;
  source?: string;
  target?: string;
  type?: string;
};

export type topology_TopologiesEdgeData = {
  source?: topology_TopologiesEdgeDataItem;
  target?: topology_TopologiesEdgeDataItem;
};

export type topology_TopologiesEdgeDataItem = {
  id?: string;
  label?: string;
  name?: string;
  type?: string;
};

export type topology_TopologiesNode = {
  data?: topology_TopologiesNodeDataItem;
  /**
   * Icon enum:cloud,router,server,switch,desktop
   */
  icon?: string;
  id?: string;
  label?: string;
  type?: string;
};

export type topology_TopologiesNodeDataItem = {
  /**
   * Icon enum:cloud,router,server,switch,desktop
   */
  icon?: string;
  id?: string;
  kind?: string;
  label?: string;
  type?: string;
};

export type topology_Topology = {
  direction?: string;
  edges?: Array<topology_TopologiesEdge>;
  nodes?: Array<topology_TopologiesNode>;
};

export type usecases_ContainersGetInputDTO = {
  deployment?: string;
  namespace?: string;
};

export type usecases_ContainersGetItem = {
  connect_url?: string;
  label?: string;
  name?: string;
  namespace?: string;
  pod?: string;
  ready?: boolean;
  restart_count?: number;
  session_id?: string;
  /**
   * Status enum: running,waiting,terminated,unknown
   */
  status?: string;
  /**
   * Type enum: containerlab,default
   */
  type?: string;
};

export type usecases_ContainersGetOutputDTO = {
  containers?: Array<usecases_ContainersGetItem>;
};

export type usecases_ContainersGetResponse = {
  error: boolean;
  msg: string;
  result?: usecases_ContainersGetOutputDTO;
};

export type usecases_TasksListInputDTO = unknown;

export type usecases_TasksListOutputDTO = {
  model: Array<queries_TaskCodeRegistryItem>;
};

export type usecases_TasksListResponse = {
  error: boolean;
  msg: string;
  result?: usecases_TasksListOutputDTO;
};

export type usecases_TopologiesCreateInputDTO = {
  redeploy?: boolean;
  task_id?: string;
  username?: string;
};

export type usecases_TopologiesCreateOutputDTO = {
  deploy_created?: boolean;
  namespace?: string;
  namespace_created?: boolean;
  user_created?: boolean;
};

export type usecases_TopologiesCreateResponse = {
  error: boolean;
  msg: string;
  result?: usecases_TopologiesCreateOutputDTO;
};

export type usecases_TopologiesDeleteInputDTO = {
  namespaces?: Array<string>;
};

export type usecases_TopologiesDeleteOutputDTO = {
  namespaces?: Array<string>;
};

export type usecases_TopologiesDeleteResponse = {
  error: boolean;
  msg: string;
  result?: usecases_TopologiesDeleteOutputDTO;
};

export type usecases_TopologiesGetInputDTO = {
  namespace?: string;
};

export type usecases_TopologiesGetOutputDTO = {
  topology?: topology_Topology;
  web_url?: string;
};

export type usecases_TopologiesGetResponse = {
  error: boolean;
  msg: string;
  result?: usecases_TopologiesGetOutputDTO;
};

export type PostV1ContainersGetData = {
  /**
   * topology namespace
   */
  form: usecases_ContainersGetInputDTO;
};

export type PostV1ContainersGetResponse = usecases_ContainersGetResponse;

export type PostV1TasksListData = {
  /**
   * tasks list info
   */
  form: usecases_TasksListInputDTO;
};

export type PostV1TasksListResponse = usecases_TasksListResponse;

export type GetV1TokensYamlResponse = string;

export type PostV1TopologiesCreateData = {
  /**
   * create params
   */
  form: usecases_TopologiesCreateInputDTO;
};

export type PostV1TopologiesCreateResponse = usecases_TopologiesCreateResponse;

export type PostV1TopologiesDeleteData = {
  /**
   * delete params
   */
  form: usecases_TopologiesDeleteInputDTO;
};

export type PostV1TopologiesDeleteResponse = usecases_TopologiesDeleteResponse;

export type PostV1TopologiesGetData = {
  /**
   * topology namespace
   */
  form: usecases_TopologiesGetInputDTO;
};

export type PostV1TopologiesGetResponse = usecases_TopologiesGetResponse;
