// This file is auto-generated by @hey-api/openapi-ts

export type queries_TaskCodeRegistryItem = {
    full_path?: string;
    id?: string;
    namespace_suffix?: string;
    title?: string;
};

export type topology_TopologiesEdge = {
    data?: topology_TopologiesEdgeData;
    id?: string;
    source?: string;
    target?: string;
    type?: string;
};

export type topology_TopologiesEdgeData = {
    source?: topology_TopologiesEdgeDataItem;
    target?: topology_TopologiesEdgeDataItem;
};

export type topology_TopologiesEdgeDataItem = {
    id?: string;
    label?: string;
    name?: string;
    type?: string;
};

export type topology_TopologiesNode = {
    /**
     * Icon enum:cloud,router,server,switch,desktop
     */
    icon?: string;
    id?: string;
    label?: string;
    type?: string;
};

export type topology_Topology = {
    direction?: string;
    edges?: Array<topology_TopologiesEdge>;
    nodes?: Array<topology_TopologiesNode>;
};

export type usecases_TasksListInputDTO = unknown;

export type usecases_TasksListOutputDTO = {
    model: Array<queries_TaskCodeRegistryItem>;
};

export type usecases_TasksListResponse = {
    error: boolean;
    msg: string;
    result?: usecases_TasksListOutputDTO;
};

export type usecases_TopologiesCreateInputDTO = {
    redeploy?: boolean;
    task_id?: string;
    user_email?: string;
};

export type usecases_TopologiesCreateOutputDTO = {
    deploy_created?: boolean;
    namespace?: string;
    namespace_created?: boolean;
    user_created?: boolean;
};

export type usecases_TopologiesCreateResponse = {
    error: boolean;
    msg: string;
    result?: usecases_TopologiesCreateOutputDTO;
};

export type usecases_TopologiesDeleteInputDTO = {
    namespaces?: Array<(string)>;
};

export type usecases_TopologiesDeleteOutputDTO = {
    namespaces?: Array<(string)>;
};

export type usecases_TopologiesDeleteResponse = {
    error: boolean;
    msg: string;
    result?: usecases_TopologiesDeleteOutputDTO;
};

export type usecases_TopologiesGetInputDTO = {
    namespace?: string;
};

export type usecases_TopologiesGetOutputDTO = {
    topology?: topology_Topology;
};

export type usecases_TopologiesGetResponse = {
    error: boolean;
    msg: string;
    result?: usecases_TopologiesGetOutputDTO;
};

export type PostV1TasksListData = {
    /**
     * tasks list info
     */
    form: usecases_TasksListInputDTO;
};

export type PostV1TasksListResponse = (usecases_TasksListResponse);

export type PostV1TopologiesCreateData = {
    /**
     * create params
     */
    form: usecases_TopologiesCreateInputDTO;
};

export type PostV1TopologiesCreateResponse = (usecases_TopologiesCreateResponse);

export type PostV1TopologiesDeleteData = {
    /**
     * delete params
     */
    form: usecases_TopologiesDeleteInputDTO;
};

export type PostV1TopologiesDeleteResponse = (usecases_TopologiesDeleteResponse);

export type PostV1TopologiesGetData = {
    /**
     * topology namespace
     */
    form: usecases_TopologiesGetInputDTO;
};

export type PostV1TopologiesGetResponse = (usecases_TopologiesGetResponse);