export const RoutesLocation = {
  login: () => '/login',
  language: () => '/lang',
  accounts: () => '/accounts',
  accountsEdit: (id = ':id') => `/accounts/edit/${id}`,
  accountsCreate: () => `/accounts/create`,
  roles: () => '/roles',
  rolesEdit: (id = ':id') => `/roles/edit/${id}`,
  rolesCreate: () => `/roles/create`,
  AuthProviders: () => '/lti-forms',
  AuthProvidersEdit: (id = ':id') => `/lti-forms/edit/${id}`,
  AuthProvidersCreate: () => `/lti-forms/create`,
  ltiRouting: () => '/lti-routing',
  ltiRoutingEdit: (id = ':id') => `/lti-routing/edit/${id}`,
  ltiRoutingCreate: () => `/lti-routing/create`,
  curlRequest: () => '/curl_request',
  curlRequestEdit: (id = ':id') => `/curl-request/edit/${id}`,
  curlRequestCreate: () => `/curl-request/create`,
  pnetServers: () => '/pnet-servers',
  pnetServersEdit: (id = ':id') => `/pnet-servers/edit/${id}`,
  pnetServersCreate: () => `/pnet-servers/create`,
  serviceCards: () => '/service-cards',
  serviceCardsEdit: (id = ':id') => `/service-cards/edit/${id}`,
  serviceCardsCreate: () => `/service-cards/create`,
  profileChangePassword: () => `/profile/password`,
  ltiRedirect: () => '/lti-redirect',
  ltiRedirectCreate: () => '/lti-redirect/create',
  ltiAttemptUser: (id = ':id') => `/lti-attempt/user/${id}`,
  ltiAttemptEdit: (id = ':id') => `/lti-attempt/edit/${id}`,
  topologyView: (namespace = ':namespace') => `/topology/${namespace}`,
  topologyDevices: (namespace = ':namespace', device = ':device') => `/topology/${namespace}/devices/${device}`,
  topologyConnect: () => `/topology`,
  docsTopologyKubectl: () => `/docs/kubectl`,
  home: () => '/'
};
