export const RoutesLocation = {
  login: () => '/login',
  language: () => '/lang',
  accounts: () => '/accounts',
  accountsEdit: (id = ':id') => `/accounts/edit/${id}`,
  accountsCreate: () => `/accounts/create`,
  roles: () => '/roles',
  rolesEdit: (id = ':id') => `/roles/edit/${id}`,
  rolesCreate: () => `/roles/create`,
  authProviders: () => '/auth-providers',
  authProvidersEdit: (id = ':id') => `/auth-providers/edit/${id}`,
  authProvidersCreate: () => `/auth-providers/create`,
  ltiRouting: () => '/lti-routing',
  ltiRoutingEdit: (id = ':id') => `/lti-routing/edit/${id}`,
  ltiRoutingCreate: () => `/lti-routing/create`,
  servers: () => '/servers',
  serversEdit: (id = ':id') => `/servers/edit/${id}`,
  serversCreate: () => `/servers/create`,
  serviceCards: () => '/service-cards',
  serviceCardsEdit: (id = ':id') => `/service-cards/edit/${id}`,
  serviceCardsCreate: () => `/service-cards/create`,
  profileChangePassword: () => `/profile/password`,
  targets: () => '/targets',
  targetsEdit: (id = ':id') => `/targets/edit/${id}`,
  targetsCreate: () => '/targets/create',
  ltiRedirect: () => '/lti-redirect',
  ltiRedirectCreate: () => '/lti-redirect/create',
  ltiAttemptUser: (id = ':id') => `/lti-attempt/user/${id}`,
  ltiAttemptEdit: (id = ':id') => `/lti-attempt/edit/${id}`,
  topologyView: (namespace = ':namespace') => `/topology/${namespace}`,
  topologyDevices: (namespace = ':namespace', device = ':device') => `/topology/${namespace}/devices/${device}`,
  topologyConnect: () => `/topology`,
  docsTopologyKubectl: () => `/docs/kubectl`,
  home: () => '/'
};
