// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "your@mail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/clabgate/api/v1/rpc/topology.get": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "List tasks. Roles: [student, admin, instructor]",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Topology"
                ],
                "summary": "list tasks",
                "parameters": [
                    {
                        "description": "topology namespace",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usecases.TopologiesGetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/usecases.TopologiesGetResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "queries.DeploymentInfo": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "ready_replicas": {
                    "type": "integer"
                },
                "replicas": {
                    "type": "integer"
                },
                "restarts": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "queries.ServiceInfo": {
            "type": "object",
            "properties": {
                "cluster_ip": {
                    "type": "string"
                },
                "external_ip": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "queries.TTYDInfo": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "usecases.TopologiesGetInputDTO": {
            "type": "object",
            "properties": {
                "attempt_number": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "usecases.TopologiesGetOutputDTO": {
            "type": "object",
            "properties": {
                "deployments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/queries.DeploymentInfo"
                    }
                },
                "services": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/queries.ServiceInfo"
                    }
                },
                "topology": {
                    "type": "string"
                },
                "ttyd": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/queries.TTYDInfo"
                    }
                }
            }
        },
        "usecases.TopologiesGetRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "default": "1"
                },
                "jsonrpc": {
                    "type": "string",
                    "default": "2.0"
                },
                "method": {
                    "type": "string",
                    "default": "topology.get"
                },
                "params": {
                    "$ref": "#/definitions/usecases.TopologiesGetInputDTO"
                }
            }
        },
        "usecases.TopologiesGetResponse": {
            "type": "object",
            "properties": {
                "error": {},
                "id": {
                    "type": "string",
                    "default": "1"
                },
                "jsonrpc": {
                    "type": "string",
                    "default": "2.0"
                },
                "result": {
                    "$ref": "#/definitions/usecases.TopologiesGetOutputDTO"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/clabgate/api",
	Schemes:          []string{},
	Title:            "Clabernetes Gate API",
	Description:      "This is an auto-generated API Docs.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
