// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "your@mail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/tasks/list": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "List tasks. Roles: [admin, instructor]",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "list tasks",
                "parameters": [
                    {
                        "description": "tasks list info",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usecases.TasksListInputDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/usecases.TasksListResponse"
                        }
                    }
                }
            }
        },
        "/v1/tokens/json": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Token cluster. Roles: [student, admin, instructor]",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Token"
                ],
                "summary": "token cluster json",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/usecases.TokenAccessGetResponse"
                        }
                    }
                }
            }
        },
        "/v1/tokens/yaml": {
            "get": {
                "description": "Token cluster. Roles: any",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Token"
                ],
                "summary": "token cluster yaml",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/usecases.TokenFileYAMLGetResponse"
                        }
                    }
                }
            }
        },
        "/v1/topologies/create": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "create personal topology. Roles: [student, admin, instructor]",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Topology"
                ],
                "summary": "create personal topologies",
                "parameters": [
                    {
                        "description": "create params",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usecases.TopologiesCreateInputDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/usecases.TopologiesCreateResponse"
                        }
                    }
                }
            }
        },
        "/v1/topologies/delete": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "delete personal topology. Roles: [student, admin, instructor]",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Topology"
                ],
                "summary": "delete personal topologies",
                "parameters": [
                    {
                        "description": "delete params",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usecases.TopologiesDeleteInputDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/usecases.TopologiesDeleteResponse"
                        }
                    }
                }
            }
        },
        "/v1/topologies/get": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "List tasks. Roles: [student, admin, instructor]",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Topology"
                ],
                "summary": "list tasks",
                "parameters": [
                    {
                        "description": "topology namespace",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usecases.TopologiesGetInputDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/usecases.TopologiesGetResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "queries.TaskCodeRegistryItem": {
            "type": "object",
            "properties": {
                "full_path": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "namespace_suffix": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "topology.TopologiesEdge": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/topology.TopologiesEdgeData"
                },
                "id": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "target": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "topology.TopologiesEdgeData": {
            "type": "object",
            "properties": {
                "source": {
                    "$ref": "#/definitions/topology.TopologiesEdgeDataItem"
                },
                "target": {
                    "$ref": "#/definitions/topology.TopologiesEdgeDataItem"
                }
            }
        },
        "topology.TopologiesEdgeDataItem": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "topology.TopologiesNode": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/topology.TopologiesNodeDataItem"
                },
                "icon": {
                    "description": "Icon enum:cloud,router,server,switch,desktop",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "topology.TopologiesNodeDataItem": {
            "type": "object",
            "properties": {
                "icon": {
                    "description": "Icon enum:cloud,router,server,switch,desktop",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "kind": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "topology.Topology": {
            "type": "object",
            "properties": {
                "direction": {
                    "type": "string"
                },
                "edges": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/topology.TopologiesEdge"
                    }
                },
                "nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/topology.TopologiesNode"
                    }
                }
            }
        },
        "usecases.TasksListInputDTO": {
            "type": "object"
        },
        "usecases.TasksListOutputDTO": {
            "type": "object",
            "required": [
                "model"
            ],
            "properties": {
                "model": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/queries.TaskCodeRegistryItem"
                    }
                }
            }
        },
        "usecases.TasksListResponse": {
            "type": "object",
            "required": [
                "error",
                "msg"
            ],
            "properties": {
                "error": {
                    "type": "boolean"
                },
                "msg": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/usecases.TasksListOutputDTO"
                }
            }
        },
        "usecases.TokenAccessGetOutputDTO": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "usecases.TokenAccessGetResponse": {
            "type": "object",
            "required": [
                "error",
                "msg"
            ],
            "properties": {
                "error": {
                    "type": "boolean"
                },
                "msg": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/usecases.TokenAccessGetOutputDTO"
                }
            }
        },
        "usecases.TokenFileYAMLGetOutputDTO": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                }
            }
        },
        "usecases.TokenFileYAMLGetResponse": {
            "type": "object",
            "required": [
                "error",
                "msg"
            ],
            "properties": {
                "error": {
                    "type": "boolean"
                },
                "msg": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/usecases.TokenFileYAMLGetOutputDTO"
                }
            }
        },
        "usecases.TopologiesCreateInputDTO": {
            "type": "object",
            "properties": {
                "redeploy": {
                    "type": "boolean"
                },
                "task_id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "usecases.TopologiesCreateOutputDTO": {
            "type": "object",
            "properties": {
                "deploy_created": {
                    "type": "boolean"
                },
                "namespace": {
                    "type": "string"
                },
                "namespace_created": {
                    "type": "boolean"
                },
                "user_created": {
                    "type": "boolean"
                }
            }
        },
        "usecases.TopologiesCreateResponse": {
            "type": "object",
            "required": [
                "error",
                "msg"
            ],
            "properties": {
                "error": {
                    "type": "boolean"
                },
                "msg": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/usecases.TopologiesCreateOutputDTO"
                }
            }
        },
        "usecases.TopologiesDeleteInputDTO": {
            "type": "object",
            "properties": {
                "namespaces": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "usecases.TopologiesDeleteOutputDTO": {
            "type": "object",
            "properties": {
                "namespaces": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "usecases.TopologiesDeleteResponse": {
            "type": "object",
            "required": [
                "error",
                "msg"
            ],
            "properties": {
                "error": {
                    "type": "boolean"
                },
                "msg": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/usecases.TopologiesDeleteOutputDTO"
                }
            }
        },
        "usecases.TopologiesGetInputDTO": {
            "type": "object",
            "properties": {
                "namespace": {
                    "type": "string"
                }
            }
        },
        "usecases.TopologiesGetOutputDTO": {
            "type": "object",
            "properties": {
                "topology": {
                    "$ref": "#/definitions/topology.Topology"
                },
                "web_url": {
                    "type": "string"
                }
            }
        },
        "usecases.TopologiesGetResponse": {
            "type": "object",
            "required": [
                "error",
                "msg"
            ],
            "properties": {
                "error": {
                    "type": "boolean"
                },
                "msg": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/usecases.TopologiesGetOutputDTO"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/clabgate/api",
	Schemes:          []string{},
	Title:            "Clabernetes Gate API",
	Description:      "This is an auto-generated API Docs.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
