basePath: /clabgate/api
definitions:
  queries.DeploymentInfo:
    properties:
      name:
        type: string
      ready_replicas:
        type: integer
      replicas:
        type: integer
      restarts:
        type: integer
      status:
        type: string
    type: object
  queries.ServiceInfo:
    properties:
      cluster_ip:
        type: string
      external_ip:
        items:
          type: string
        type: array
      name:
        type: string
      type:
        type: string
    type: object
  queries.TTYDInfo:
    properties:
      name:
        type: string
      url:
        type: string
    type: object
  usecases.NodeActionInputDTO:
    properties:
      actions:
        items:
          $ref: '#/definitions/usecases.NodeActionItem'
        type: array
      session_id:
        type: string
    required:
    - session_id
    type: object
  usecases.NodeActionItem:
    properties:
      action:
        description: 'enum: wipe,restart'
        type: string
      node:
        type: string
    type: object
  usecases.NodeActionOutputDTO:
    properties:
      count:
        type: integer
    type: object
  usecases.NodeActionRequest:
    properties:
      id:
        default: "1"
        type: string
      jsonrpc:
        default: "2.0"
        type: string
      method:
        default: nodes.action
        type: string
      params:
        $ref: '#/definitions/usecases.NodeActionInputDTO'
    type: object
  usecases.NodeActionResponse:
    properties:
      error: {}
      id:
        default: "1"
        type: string
      jsonrpc:
        default: "2.0"
        type: string
      result:
        $ref: '#/definitions/usecases.NodeActionOutputDTO'
    type: object
  usecases.TopologiesGetInputDTO:
    properties:
      session_id:
        type: string
    required:
    - session_id
    type: object
  usecases.TopologiesGetOutputDTO:
    properties:
      deployments:
        items:
          $ref: '#/definitions/queries.DeploymentInfo'
        type: array
      services:
        items:
          $ref: '#/definitions/queries.ServiceInfo'
        type: array
      topology:
        type: string
      ttyd:
        items:
          $ref: '#/definitions/queries.TTYDInfo'
        type: array
    type: object
  usecases.TopologiesGetRequest:
    properties:
      id:
        default: "1"
        type: string
      jsonrpc:
        default: "2.0"
        type: string
      method:
        default: topology.get
        type: string
      params:
        $ref: '#/definitions/usecases.TopologiesGetInputDTO'
    type: object
  usecases.TopologiesGetResponse:
    properties:
      error: {}
      id:
        default: "1"
        type: string
      jsonrpc:
        default: "2.0"
        type: string
      result:
        $ref: '#/definitions/usecases.TopologiesGetOutputDTO'
    type: object
info:
  contact:
    email: your@mail.com
    name: API Support
  description: This is an auto-generated API Docs.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Clabernetes Gate API
  version: "1.0"
paths:
  /clabgate/api/v1/rpc/node.action:
    post:
      consumes:
      - application/json
      description: 'Restart or wipe pods. Roles: [admin, instructor, student]'
      parameters:
      - description: node action
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/usecases.NodeActionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/usecases.NodeActionResponse'
      security:
      - ApiKeyAuth: []
      summary: node action
      tags:
      - Node
  /clabgate/api/v1/rpc/topology.get:
    post:
      consumes:
      - application/json
      description: 'List tasks. Roles: [student, admin, instructor]'
      parameters:
      - description: topology namespace
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/usecases.TopologiesGetRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/usecases.TopologiesGetResponse'
      security:
      - ApiKeyAuth: []
      summary: list tasks
      tags:
      - Topology
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
