basePath: /clabgate/api
definitions:
  queries.TaskCodeRegistryItem:
    properties:
      full_path:
        type: string
      id:
        type: string
      namespace_suffix:
        type: string
      title:
        type: string
    type: object
  topology.TopologiesEdge:
    properties:
      data:
        $ref: '#/definitions/topology.TopologiesEdgeData'
      id:
        type: string
      source:
        type: string
      target:
        type: string
      type:
        type: string
    type: object
  topology.TopologiesEdgeData:
    properties:
      source:
        $ref: '#/definitions/topology.TopologiesEdgeDataItem'
      target:
        $ref: '#/definitions/topology.TopologiesEdgeDataItem'
    type: object
  topology.TopologiesEdgeDataItem:
    properties:
      id:
        type: string
      label:
        type: string
      name:
        type: string
      type:
        type: string
    type: object
  topology.TopologiesNode:
    properties:
      data:
        $ref: '#/definitions/topology.TopologiesNodeDataItem'
      icon:
        description: Icon enum:cloud,router,server,switch,desktop
        type: string
      id:
        type: string
      label:
        type: string
      type:
        type: string
    type: object
  topology.TopologiesNodeDataItem:
    properties:
      icon:
        description: Icon enum:cloud,router,server,switch,desktop
        type: string
      id:
        type: string
      kind:
        type: string
      label:
        type: string
      type:
        type: string
    type: object
  topology.Topology:
    properties:
      direction:
        type: string
      edges:
        items:
          $ref: '#/definitions/topology.TopologiesEdge'
        type: array
      nodes:
        items:
          $ref: '#/definitions/topology.TopologiesNode'
        type: array
    type: object
  usecases.ContainersGetInputDTO:
    properties:
      deployment:
        type: string
      namespace:
        type: string
    type: object
  usecases.ContainersGetItem:
    properties:
      connect_url:
        type: string
      label:
        type: string
      name:
        type: string
      namespace:
        type: string
      pod:
        type: string
      ready:
        type: boolean
      restart_count:
        type: integer
      session_id:
        type: string
      status:
        description: 'Status enum: running,waiting,terminated,unknown'
        type: string
    type: object
  usecases.ContainersGetOutputDTO:
    properties:
      containers:
        items:
          $ref: '#/definitions/usecases.ContainersGetItem'
        type: array
    type: object
  usecases.ContainersGetResponse:
    properties:
      error:
        type: boolean
      msg:
        type: string
      result:
        $ref: '#/definitions/usecases.ContainersGetOutputDTO'
    required:
    - error
    - msg
    type: object
  usecases.TasksListInputDTO:
    type: object
  usecases.TasksListOutputDTO:
    properties:
      model:
        items:
          $ref: '#/definitions/queries.TaskCodeRegistryItem'
        type: array
    required:
    - model
    type: object
  usecases.TasksListResponse:
    properties:
      error:
        type: boolean
      msg:
        type: string
      result:
        $ref: '#/definitions/usecases.TasksListOutputDTO'
    required:
    - error
    - msg
    type: object
  usecases.TokenAccessGetOutputDTO:
    properties:
      token:
        type: string
    type: object
  usecases.TokenAccessGetResponse:
    properties:
      error:
        type: boolean
      msg:
        type: string
      result:
        $ref: '#/definitions/usecases.TokenAccessGetOutputDTO'
    required:
    - error
    - msg
    type: object
  usecases.TokenFileYAMLGetOutputDTO:
    properties:
      content:
        type: string
      filename:
        type: string
    type: object
  usecases.TokenFileYAMLGetResponse:
    properties:
      error:
        type: boolean
      msg:
        type: string
      result:
        $ref: '#/definitions/usecases.TokenFileYAMLGetOutputDTO'
    required:
    - error
    - msg
    type: object
  usecases.TopologiesCreateInputDTO:
    properties:
      redeploy:
        type: boolean
      task_id:
        type: string
      username:
        type: string
    type: object
  usecases.TopologiesCreateOutputDTO:
    properties:
      deploy_created:
        type: boolean
      namespace:
        type: string
      namespace_created:
        type: boolean
      user_created:
        type: boolean
    type: object
  usecases.TopologiesCreateResponse:
    properties:
      error:
        type: boolean
      msg:
        type: string
      result:
        $ref: '#/definitions/usecases.TopologiesCreateOutputDTO'
    required:
    - error
    - msg
    type: object
  usecases.TopologiesDeleteInputDTO:
    properties:
      namespaces:
        items:
          type: string
        type: array
    type: object
  usecases.TopologiesDeleteOutputDTO:
    properties:
      namespaces:
        items:
          type: string
        type: array
    type: object
  usecases.TopologiesDeleteResponse:
    properties:
      error:
        type: boolean
      msg:
        type: string
      result:
        $ref: '#/definitions/usecases.TopologiesDeleteOutputDTO'
    required:
    - error
    - msg
    type: object
  usecases.TopologiesGetInputDTO:
    properties:
      namespace:
        type: string
    type: object
  usecases.TopologiesGetOutputDTO:
    properties:
      topology:
        $ref: '#/definitions/topology.Topology'
      web_url:
        type: string
    type: object
  usecases.TopologiesGetResponse:
    properties:
      error:
        type: boolean
      msg:
        type: string
      result:
        $ref: '#/definitions/usecases.TopologiesGetOutputDTO'
    required:
    - error
    - msg
    type: object
info:
  contact:
    email: your@mail.com
    name: API Support
  description: This is an auto-generated API Docs.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Clabernetes Gate API
  version: "1.0"
paths:
  /v1/containers/get:
    post:
      consumes:
      - application/json
      description: Describe device topology
      parameters:
      - description: topology namespace
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/usecases.ContainersGetInputDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/usecases.ContainersGetResponse'
      security:
      - ApiKeyAuth: []
      summary: describe device topology
      tags:
      - Device
  /v1/tasks/list:
    post:
      consumes:
      - application/json
      description: 'List tasks. Roles: [admin, instructor]'
      parameters:
      - description: tasks list info
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/usecases.TasksListInputDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/usecases.TasksListResponse'
      security:
      - ApiKeyAuth: []
      summary: list tasks
      tags:
      - Tasks
  /v1/tokens/json:
    get:
      consumes:
      - application/json
      description: 'Token cluster. Roles: [student, admin, instructor]'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/usecases.TokenAccessGetResponse'
      security:
      - ApiKeyAuth: []
      summary: token cluster json
      tags:
      - Token
  /v1/tokens/yaml:
    get:
      consumes:
      - application/json
      description: 'Token cluster. Roles: any'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/usecases.TokenFileYAMLGetResponse'
      summary: token cluster yaml
      tags:
      - Token
  /v1/topologies/create:
    post:
      consumes:
      - application/json
      description: 'create personal topology. Roles: [student, admin, instructor]'
      parameters:
      - description: create params
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/usecases.TopologiesCreateInputDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/usecases.TopologiesCreateResponse'
      security:
      - ApiKeyAuth: []
      summary: create personal topologies
      tags:
      - Topology
  /v1/topologies/delete:
    post:
      consumes:
      - application/json
      description: 'delete personal topology. Roles: [student, admin, instructor]'
      parameters:
      - description: delete params
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/usecases.TopologiesDeleteInputDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/usecases.TopologiesDeleteResponse'
      security:
      - ApiKeyAuth: []
      summary: delete personal topologies
      tags:
      - Topology
  /v1/topologies/get:
    post:
      consumes:
      - application/json
      description: 'List tasks. Roles: [student, admin, instructor]'
      parameters:
      - description: topology namespace
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/usecases.TopologiesGetInputDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/usecases.TopologiesGetResponse'
      security:
      - ApiKeyAuth: []
      summary: list tasks
      tags:
      - Topology
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
