// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "your@mail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/lti-attempt/create": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create or get exists lti_attempt. Roles: [admin, instructor, student]",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LTIAttempt"
                ],
                "summary": "create lti_attempt",
                "parameters": [
                    {
                        "description": "lti_attempt form info",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usecases.LTIAttemptCreateInputDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/usecases.LTIAttemptCreateResponse"
                        }
                    }
                }
            }
        },
        "/v1/lti-attempt/delete": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete lti_attempt.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LTIAttempt"
                ],
                "summary": "delete lti_attempt",
                "parameters": [
                    {
                        "description": "lti_attempt id",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usecases.LTIAttemptDeleteInputDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/usecases.LTIAttemptDeleteResponse"
                        }
                    }
                }
            }
        },
        "/v1/lti-attempt/edit": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Edit lti_attempt.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LTIAttempt"
                ],
                "summary": "edit lti_attempt",
                "parameters": [
                    {
                        "description": "lti_attempt form info",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usecases.LTIAttemptEditInputDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/usecases.LTIAttemptEditResponse"
                        }
                    }
                }
            }
        },
        "/v1/lti-attempt/get": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get lti_attempt.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LTIAttempt"
                ],
                "summary": "get lti_attempt",
                "parameters": [
                    {
                        "description": "lti_attempt id",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usecases.LTIAttemptGetInputDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/usecases.LTIAttemptGetResponse"
                        }
                    }
                }
            }
        },
        "/v1/lti-attempt/list": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "List lti_attempt.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LTIAttempt"
                ],
                "summary": "list lti_attempt",
                "parameters": [
                    {
                        "description": "lti_attempt list info",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usecases.LTIAttemptListInputDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/usecases.LTIAttemptListResponse"
                        }
                    }
                }
            }
        },
        "/v1/lti-form/delete": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete lti_form. Roles: [admin]",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LTIForm"
                ],
                "summary": "delete lti_form",
                "parameters": [
                    {
                        "description": "lti_form id",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usecases.LTIFormDeleteInputDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/usecases.LTIFormDeleteResponse"
                        }
                    }
                }
            }
        },
        "/v1/lti-form/get": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get lti_form. Roles [admin]",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LTIForm"
                ],
                "summary": "get lti_form",
                "parameters": [
                    {
                        "description": "lti_form id",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usecases.LTIFormGetInputDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/usecases.LTIFormGetResponse"
                        }
                    }
                }
            }
        },
        "/v1/lti-form/list": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "List lti_form. Roles: [admin]",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LTIForm"
                ],
                "summary": "list lti_form",
                "parameters": [
                    {
                        "description": "lti_form list info",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usecases.LTIFormListInputDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/usecases.LTIFormListResponse"
                        }
                    }
                }
            }
        },
        "/v1/lti-form/upsert": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create lti_form. Roles: [admin]",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LTIForm"
                ],
                "summary": "create lti_form",
                "parameters": [
                    {
                        "description": "lti_form form info",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usecases.LTIFormEditInputDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/usecases.LTIFormEditResponse"
                        }
                    }
                }
            }
        },
        "/v1/lti-routing/delete": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete lti_routing. Roles [admin, instructor]",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LTIRouting"
                ],
                "summary": "delete lti_routing",
                "parameters": [
                    {
                        "description": "lti_routing id",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usecases.LTIRoutingDeleteInputDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/usecases.LTIRoutingDeleteResponse"
                        }
                    }
                }
            }
        },
        "/v1/lti-routing/get": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get lti_routing. Roles [admin, instructor]",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LTIRouting"
                ],
                "summary": "get lti_routing",
                "parameters": [
                    {
                        "description": "lti_routing id",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usecases.LTIRoutingGetInputDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/usecases.LTIRoutingGetResponse"
                        }
                    }
                }
            }
        },
        "/v1/lti-routing/list": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "List lti_routing. Roles [admin, instructor]",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LTIRouting"
                ],
                "summary": "list lti_routing",
                "parameters": [
                    {
                        "description": "lti_routing list info",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usecases.LTIRoutingListInputDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/usecases.LTIRoutingListResponse"
                        }
                    }
                }
            }
        },
        "/v1/lti-routing/upsert": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create lti_routing. Roles [admin, instructor]",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LTIRouting"
                ],
                "summary": "create lti_routing",
                "parameters": [
                    {
                        "description": "lti_routing form info",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usecases.LTIRoutingEditInputDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/usecases.LTIRoutingEditResponse"
                        }
                    }
                }
            }
        },
        "/v1/pnet-server-queue/list": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "List pnet_server_queue. Roles: [admin, instructor]",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PNETServerQueue"
                ],
                "summary": "list pnet_server_queue",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/round_queue_pool_pnet.RoundQueuePoolPnetListResponse"
                        }
                    }
                }
            }
        },
        "/v1/pnet-server-queue/upsert": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create pnet_server_queue. Roles: [admin, instructor]",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PNETServerQueue"
                ],
                "summary": "create pnet_server_queue",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/round_queue_pool_pnet.RoundQueuePoolPnetUpsertResponse"
                        }
                    }
                }
            }
        },
        "/v1/pnet-server/delete": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete pnet_server. Roles: [admin]",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PNETServer"
                ],
                "summary": "delete pnet_server",
                "parameters": [
                    {
                        "description": "pnet_server id",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usecases.PNETServerDeleteInputDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/usecases.PNETServerDeleteResponse"
                        }
                    }
                }
            }
        },
        "/v1/pnet-server/get": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get pnet_server. Roles: [admin, instructor]",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PNETServer"
                ],
                "summary": "get pnet_server",
                "parameters": [
                    {
                        "description": "pnet_server id",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usecases.PNETServerGetInputDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/usecases.PNETServerGetResponse"
                        }
                    }
                }
            }
        },
        "/v1/pnet-server/list": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "List pnet_server. Roles: [admin, instructor]",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PNETServer"
                ],
                "summary": "list pnet_server",
                "parameters": [
                    {
                        "description": "pnet_server list info",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usecases.PNETServerListInputDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/usecases.PNETServerListResponse"
                        }
                    }
                }
            }
        },
        "/v1/pnet-server/upsert": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create pnet_server. Roles [admin]",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PNETServer"
                ],
                "summary": "create pnet_server",
                "parameters": [
                    {
                        "description": "pnet_server form info",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usecases.PNETServerEditInputDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/usecases.PNETServerEditResponse"
                        }
                    }
                }
            }
        },
        "/v1/token/check": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "View data access token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Token"
                ],
                "summary": "view data from access token",
                "parameters": [
                    {
                        "description": "renew token form info",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RenewManagerInputDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.RenewManagerUserResponse"
                        }
                    }
                }
            }
        },
        "/v1/token/login": {
            "post": {
                "description": "Login by email and password.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Token"
                ],
                "summary": "login by email and password",
                "parameters": [
                    {
                        "description": "credentials form info",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RenewManagerCredentialsInputDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.RenewManagerResponse"
                        }
                    }
                }
            }
        },
        "/v1/token/logout": {
            "post": {
                "description": "Logout.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Token"
                ],
                "summary": "logout",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.RenewManagerResponse"
                        }
                    }
                }
            }
        },
        "/v1/token/password_change": {
            "post": {
                "description": "Change password.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Token"
                ],
                "summary": "change password",
                "parameters": [
                    {
                        "description": "credentials form info",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usecases.UserPasswordChangeInputDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/usecases.UserPasswordRecoverResponse"
                        }
                    }
                }
            }
        },
        "/v1/token/renew": {
            "post": {
                "description": "Renew access and refresh tokens.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Token"
                ],
                "summary": "renew access and refresh tokens",
                "parameters": [
                    {
                        "description": "renew token form info",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RenewManagerInputDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.RenewManagerResponse"
                        }
                    }
                }
            }
        },
        "/v1/user/get": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get user. Roles[admin, instructor]",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "get user",
                "parameters": [
                    {
                        "description": "user id",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usecases.UserGetInputDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/usecases.UserGetResponse"
                        }
                    }
                }
            }
        },
        "/v1/user/list": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "List user. Roles[admin, instructor]",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "list user",
                "parameters": [
                    {
                        "description": "user list info",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usecases.UserListInputDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/usecases.UserListResponse"
                        }
                    }
                }
            }
        },
        "/v1/user/upsert": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create user. Roles[admin, instructor]",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "create user",
                "parameters": [
                    {
                        "description": "user form info",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usecases.UserEditInputDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/usecases.UserEditResponse"
                        }
                    }
                }
            }
        },
        "/v2/lti/launch": {
            "get": {
                "description": "инициализация подключения к LTI.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LTI"
                ],
                "summary": "инициализация подключения к LTI",
                "responses": {
                    "302": {
                        "description": "Found"
                    }
                }
            },
            "post": {
                "description": "инициализация подключения к LTI.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LTI"
                ],
                "summary": "инициализация подключения к LTI",
                "responses": {
                    "302": {
                        "description": "Found"
                    }
                }
            }
        },
        "/v2/lti/login": {
            "get": {
                "description": "аутентификация LTI.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LTI"
                ],
                "summary": "аутентификация через LTI",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "post": {
                "description": "аутентификация LTI.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LTI"
                ],
                "summary": "аутентификация через LTI",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.RenewManagerCredentialsInputDTO": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "auth.RenewManagerInputDTO": {
            "type": "object",
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "auth.RenewManagerResponse": {
            "type": "object",
            "required": [
                "error",
                "msg"
            ],
            "properties": {
                "error": {
                    "type": "boolean"
                },
                "msg": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/auth.Tokens"
                }
            }
        },
        "auth.RenewManagerUserResponse": {
            "type": "object",
            "required": [
                "error",
                "msg"
            ],
            "properties": {
                "error": {
                    "type": "boolean"
                },
                "msg": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/auth.TokenPublicData"
                }
            }
        },
        "auth.TokenDataWithExp": {
            "type": "object",
            "properties": {
                "exp": {
                    "type": "integer"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "auth.TokenPublicData": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "exp": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "last_launch_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "auth.Tokens": {
            "type": "object",
            "properties": {
                "access": {
                    "$ref": "#/definitions/auth.TokenDataWithExp"
                },
                "refresh": {
                    "$ref": "#/definitions/auth.TokenDataWithExp"
                }
            }
        },
        "models.LTIAttempt": {
            "type": "object",
            "required": [
                "created_at",
                "updated_at",
                "updated_at"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lti_routing_id": {
                    "type": "integer"
                },
                "pnet_server_id": {
                    "type": "integer"
                },
                "room_number": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.LTIAttemptListItem": {
            "type": "object",
            "required": [
                "created_at",
                "updated_at",
                "updated_at"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lti_routing_id": {
                    "type": "integer"
                },
                "pnet_server_id": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.LTIForm": {
            "type": "object",
            "required": [
                "base_uri",
                "created_at",
                "key_set_uri",
                "lti_auth_login_uri",
                "lti_auth_token_uri",
                "lti_client_id",
                "lti_deployment_id",
                "name",
                "private_key",
                "public_key",
                "target_link_uri",
                "updated_at"
            ],
            "properties": {
                "base_uri": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "key_set_uri": {
                    "type": "string"
                },
                "lti_auth_login_uri": {
                    "type": "string"
                },
                "lti_auth_token_uri": {
                    "type": "string"
                },
                "lti_client_id": {
                    "type": "string"
                },
                "lti_deployment_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "private_key": {
                    "type": "string"
                },
                "public_key": {
                    "type": "string"
                },
                "target_link_uri": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.LTIFormListItem": {
            "type": "object",
            "required": [
                "created_at",
                "lti_client_id",
                "lti_deployment_id",
                "name",
                "updated_at"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lti_client_id": {
                    "type": "string"
                },
                "lti_deployment_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.LTIRouting": {
            "type": "object",
            "required": [
                "created_at",
                "updated_at"
            ],
            "properties": {
                "collaboration": {
                    "description": "Параметры",
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lti_description": {
                    "type": "string"
                },
                "lti_params_task": {
                    "type": "string"
                },
                "lti_task_id": {
                    "type": "string"
                },
                "lti_title": {
                    "description": "LTI Params",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "pinned_session_minutes": {
                    "type": "integer"
                },
                "pnet_labs_path": {
                    "type": "string"
                },
                "pnet_test_path": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.LTIRoutingListItem": {
            "type": "object",
            "required": [
                "created_at",
                "updated_at"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.PNETServer": {
            "type": "object",
            "required": [
                "created_at",
                "updated_at"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "last_count_users": {
                    "type": "integer"
                },
                "last_online_status": {
                    "type": "string"
                },
                "max_count_users_limit": {
                    "type": "integer"
                },
                "minutes_for_disconnect": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "unit_rate": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "models.PNETServerListItem": {
            "type": "object",
            "required": [
                "created_at",
                "updated_at"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "last_count_users": {
                    "type": "integer"
                },
                "last_online_status": {
                    "type": "string"
                },
                "max_count_users_limit": {
                    "type": "integer"
                },
                "minutes_for_disconnect": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "unit_rate": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "models.User": {
            "type": "object",
            "required": [
                "created_at",
                "group_name",
                "updated_at",
                "user_role"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "group_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_launch_id": {
                    "type": "string"
                },
                "lti_user_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_role": {
                    "type": "string"
                }
            }
        },
        "models.UserListItem": {
            "type": "object",
            "required": [
                "created_at",
                "group_name",
                "updated_at",
                "user_role"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "group_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lti_user_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_role": {
                    "type": "string"
                }
            }
        },
        "queries.RoundQueuePoolPnetListItem": {
            "type": "object",
            "required": [
                "connected_at",
                "last_used",
                "type"
            ],
            "properties": {
                "connected_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_used": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "round_queue_pool_pnet.RoundQueuePoolPnetListOutputDTO": {
            "type": "object",
            "required": [
                "model"
            ],
            "properties": {
                "model": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/queries.RoundQueuePoolPnetListItem"
                    }
                }
            }
        },
        "round_queue_pool_pnet.RoundQueuePoolPnetListResponse": {
            "type": "object",
            "required": [
                "error",
                "msg"
            ],
            "properties": {
                "error": {
                    "type": "boolean"
                },
                "msg": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/round_queue_pool_pnet.RoundQueuePoolPnetListOutputDTO"
                }
            }
        },
        "round_queue_pool_pnet.RoundQueuePoolPnetUpsertOutputDTO": {
            "type": "object"
        },
        "round_queue_pool_pnet.RoundQueuePoolPnetUpsertResponse": {
            "type": "object",
            "required": [
                "error",
                "msg"
            ],
            "properties": {
                "error": {
                    "type": "boolean"
                },
                "msg": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/round_queue_pool_pnet.RoundQueuePoolPnetUpsertOutputDTO"
                }
            }
        },
        "usecases.LTIAttemptCreateInputDTO": {
            "type": "object"
        },
        "usecases.LTIAttemptCreateOutputDTO": {
            "type": "object",
            "properties": {
                "auto_redirect": {
                    "type": "boolean"
                },
                "collaboration": {
                    "type": "integer"
                },
                "members": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.UserListItem"
                    }
                },
                "next_url": {
                    "type": "string"
                },
                "room_number": {
                    "type": "integer"
                }
            }
        },
        "usecases.LTIAttemptCreateResponse": {
            "type": "object",
            "required": [
                "error",
                "msg"
            ],
            "properties": {
                "error": {
                    "type": "boolean"
                },
                "msg": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/usecases.LTIAttemptCreateOutputDTO"
                }
            }
        },
        "usecases.LTIAttemptDeleteInputDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "usecases.LTIAttemptDeleteResponse": {
            "type": "object",
            "required": [
                "error",
                "msg"
            ],
            "properties": {
                "error": {
                    "type": "boolean"
                },
                "msg": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/usecases.LTIAttemptDeleteInputDTO"
                }
            }
        },
        "usecases.LTIAttemptEditInputDTO": {
            "type": "object",
            "required": [
                "name",
                "token",
                "url"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "unit_rate": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "usecases.LTIAttemptEditOutputDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "usecases.LTIAttemptEditResponse": {
            "type": "object",
            "required": [
                "error",
                "msg"
            ],
            "properties": {
                "error": {
                    "type": "boolean"
                },
                "msg": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/usecases.LTIAttemptEditOutputDTO"
                }
            }
        },
        "usecases.LTIAttemptGetInputDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "usecases.LTIAttemptGetOutputDTO": {
            "type": "object",
            "properties": {
                "model": {
                    "$ref": "#/definitions/models.LTIAttempt"
                }
            }
        },
        "usecases.LTIAttemptGetResponse": {
            "type": "object",
            "required": [
                "error",
                "msg"
            ],
            "properties": {
                "error": {
                    "type": "boolean"
                },
                "msg": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/usecases.LTIAttemptGetOutputDTO"
                }
            }
        },
        "usecases.LTIAttemptListInputDTO": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "search": {
                    "type": "string"
                }
            }
        },
        "usecases.LTIAttemptListOutputDTO": {
            "type": "object",
            "required": [
                "model",
                "total_count"
            ],
            "properties": {
                "model": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.LTIAttemptListItem"
                    }
                },
                "total_count": {
                    "type": "integer"
                }
            }
        },
        "usecases.LTIAttemptListResponse": {
            "type": "object",
            "required": [
                "error",
                "msg"
            ],
            "properties": {
                "error": {
                    "type": "boolean"
                },
                "msg": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/usecases.LTIAttemptListOutputDTO"
                }
            }
        },
        "usecases.LTIFormDeleteInputDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "usecases.LTIFormDeleteResponse": {
            "type": "object",
            "required": [
                "error",
                "msg"
            ],
            "properties": {
                "error": {
                    "type": "boolean"
                },
                "msg": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/usecases.LTIFormDeleteInputDTO"
                }
            }
        },
        "usecases.LTIFormEditInputDTO": {
            "type": "object",
            "required": [
                "auth_login_uri",
                "auth_token_uri",
                "base_uri",
                "client_id",
                "deployment_id",
                "key_set_uri",
                "name",
                "target_link_uri"
            ],
            "properties": {
                "auth_login_uri": {
                    "type": "string"
                },
                "auth_token_uri": {
                    "type": "string"
                },
                "base_uri": {
                    "type": "string"
                },
                "client_id": {
                    "type": "string"
                },
                "deployment_id": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "key_set_uri": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "target_link_uri": {
                    "type": "string"
                }
            }
        },
        "usecases.LTIFormEditOutputDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "usecases.LTIFormEditResponse": {
            "type": "object",
            "required": [
                "error",
                "msg"
            ],
            "properties": {
                "error": {
                    "type": "boolean"
                },
                "msg": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/usecases.LTIFormEditOutputDTO"
                }
            }
        },
        "usecases.LTIFormGetInputDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "usecases.LTIFormGetOutputDTO": {
            "type": "object",
            "properties": {
                "model": {
                    "$ref": "#/definitions/models.LTIForm"
                }
            }
        },
        "usecases.LTIFormGetResponse": {
            "type": "object",
            "required": [
                "error",
                "msg"
            ],
            "properties": {
                "error": {
                    "type": "boolean"
                },
                "msg": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/usecases.LTIFormGetOutputDTO"
                }
            }
        },
        "usecases.LTIFormListInputDTO": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "search": {
                    "type": "string"
                }
            }
        },
        "usecases.LTIFormListOutputDTO": {
            "type": "object",
            "required": [
                "model",
                "total_count"
            ],
            "properties": {
                "model": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.LTIFormListItem"
                    }
                },
                "total_count": {
                    "type": "integer"
                }
            }
        },
        "usecases.LTIFormListResponse": {
            "type": "object",
            "required": [
                "error",
                "msg"
            ],
            "properties": {
                "error": {
                    "type": "boolean"
                },
                "msg": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/usecases.LTIFormListOutputDTO"
                }
            }
        },
        "usecases.LTIRoutingDeleteInputDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "usecases.LTIRoutingDeleteResponse": {
            "type": "object",
            "required": [
                "error",
                "msg"
            ],
            "properties": {
                "error": {
                    "type": "boolean"
                },
                "msg": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/usecases.LTIRoutingDeleteInputDTO"
                }
            }
        },
        "usecases.LTIRoutingEditInputDTO": {
            "type": "object",
            "properties": {
                "collaboration": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "lti_description": {
                    "type": "string"
                },
                "lti_params_task": {
                    "type": "string"
                },
                "lti_task_id": {
                    "type": "string"
                },
                "lti_title": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "pinned_session_minutes": {
                    "type": "integer"
                },
                "pnet_labs_path": {
                    "type": "string"
                },
                "pnet_test_path": {
                    "type": "string"
                }
            }
        },
        "usecases.LTIRoutingEditOutputDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "usecases.LTIRoutingEditResponse": {
            "type": "object",
            "required": [
                "error",
                "msg"
            ],
            "properties": {
                "error": {
                    "type": "boolean"
                },
                "msg": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/usecases.LTIRoutingEditOutputDTO"
                }
            }
        },
        "usecases.LTIRoutingGetInputDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "usecases.LTIRoutingGetOutputDTO": {
            "type": "object",
            "properties": {
                "model": {
                    "$ref": "#/definitions/models.LTIRouting"
                }
            }
        },
        "usecases.LTIRoutingGetResponse": {
            "type": "object",
            "required": [
                "error",
                "msg"
            ],
            "properties": {
                "error": {
                    "type": "boolean"
                },
                "msg": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/usecases.LTIRoutingGetOutputDTO"
                }
            }
        },
        "usecases.LTIRoutingListInputDTO": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "search": {
                    "type": "string"
                }
            }
        },
        "usecases.LTIRoutingListOutputDTO": {
            "type": "object",
            "required": [
                "model",
                "total_count"
            ],
            "properties": {
                "model": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.LTIRoutingListItem"
                    }
                },
                "total_count": {
                    "type": "integer"
                }
            }
        },
        "usecases.LTIRoutingListResponse": {
            "type": "object",
            "required": [
                "error",
                "msg"
            ],
            "properties": {
                "error": {
                    "type": "boolean"
                },
                "msg": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/usecases.LTIRoutingListOutputDTO"
                }
            }
        },
        "usecases.PNETServerDeleteInputDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "usecases.PNETServerDeleteResponse": {
            "type": "object",
            "required": [
                "error",
                "msg"
            ],
            "properties": {
                "error": {
                    "type": "boolean"
                },
                "msg": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/usecases.PNETServerDeleteInputDTO"
                }
            }
        },
        "usecases.PNETServerEditInputDTO": {
            "type": "object",
            "required": [
                "name",
                "url"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "max_count_users_limit": {
                    "type": "integer"
                },
                "minutes_for_disconnect": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "unit_rate": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "usecases.PNETServerEditOutputDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "usecases.PNETServerEditResponse": {
            "type": "object",
            "required": [
                "error",
                "msg"
            ],
            "properties": {
                "error": {
                    "type": "boolean"
                },
                "msg": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/usecases.PNETServerEditOutputDTO"
                }
            }
        },
        "usecases.PNETServerGetInputDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "usecases.PNETServerGetOutputDTO": {
            "type": "object",
            "properties": {
                "model": {
                    "$ref": "#/definitions/models.PNETServer"
                }
            }
        },
        "usecases.PNETServerGetResponse": {
            "type": "object",
            "required": [
                "error",
                "msg"
            ],
            "properties": {
                "error": {
                    "type": "boolean"
                },
                "msg": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/usecases.PNETServerGetOutputDTO"
                }
            }
        },
        "usecases.PNETServerListInputDTO": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "order_by": {
                    "description": "The type of orderBy\nenum: createdAt,unitRate,lastCountUsers",
                    "type": "string"
                },
                "search": {
                    "type": "string"
                },
                "status": {
                    "description": "The type of status\nenum: all,active",
                    "type": "string"
                }
            }
        },
        "usecases.PNETServerListOutputDTO": {
            "type": "object",
            "required": [
                "model",
                "total_count"
            ],
            "properties": {
                "model": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.PNETServerListItem"
                    }
                },
                "total_count": {
                    "type": "integer"
                }
            }
        },
        "usecases.PNETServerListResponse": {
            "type": "object",
            "required": [
                "error",
                "msg"
            ],
            "properties": {
                "error": {
                    "type": "boolean"
                },
                "msg": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/usecases.PNETServerListOutputDTO"
                }
            }
        },
        "usecases.UserEditInputDTO": {
            "type": "object",
            "required": [
                "email",
                "name"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "group_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "lti_user_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "user_role": {
                    "type": "string"
                }
            }
        },
        "usecases.UserEditOutputDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "usecases.UserEditResponse": {
            "type": "object",
            "required": [
                "error",
                "msg"
            ],
            "properties": {
                "error": {
                    "type": "boolean"
                },
                "msg": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/usecases.UserEditOutputDTO"
                }
            }
        },
        "usecases.UserGetInputDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "usecases.UserGetOutputDTO": {
            "type": "object",
            "properties": {
                "model": {
                    "$ref": "#/definitions/models.User"
                }
            }
        },
        "usecases.UserGetResponse": {
            "type": "object",
            "required": [
                "error",
                "msg"
            ],
            "properties": {
                "error": {
                    "type": "boolean"
                },
                "msg": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/usecases.UserGetOutputDTO"
                }
            }
        },
        "usecases.UserListInputDTO": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "search": {
                    "type": "string"
                }
            }
        },
        "usecases.UserListOutputDTO": {
            "type": "object",
            "required": [
                "model",
                "total_count"
            ],
            "properties": {
                "model": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.UserListItem"
                    }
                },
                "total_count": {
                    "type": "integer"
                }
            }
        },
        "usecases.UserListResponse": {
            "type": "object",
            "required": [
                "error",
                "msg"
            ],
            "properties": {
                "error": {
                    "type": "boolean"
                },
                "msg": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/usecases.UserListOutputDTO"
                }
            }
        },
        "usecases.UserPasswordChangeInputDTO": {
            "type": "object",
            "properties": {
                "again_password": {
                    "type": "string"
                },
                "new_password": {
                    "type": "string"
                },
                "old_password": {
                    "type": "string"
                }
            }
        },
        "usecases.UserPasswordChangeOutputDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "usecases.UserPasswordRecoverResponse": {
            "type": "object",
            "required": [
                "error",
                "msg"
            ],
            "properties": {
                "error": {
                    "type": "boolean"
                },
                "msg": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/usecases.UserPasswordChangeOutputDTO"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "API",
	Description:      "This is an auto-generated API Docs.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
