apiVersion: v2
description: Nixys universal Helm chart for deploy your apps to Kubernetes
name: universal-chart
version: 2.8.1
home: https://github.com/maintainer64/cms-labs-api
sources:
  - https://github.com/maintainer64/cms-labs-api/tree/main/k8s/base-chart
annotations:
  org.opencontainers.image.source: https://github.com/maintainer64/cms-labs-api
  org.opencontainers.image.description: Reusable deployment chart used by CMS Labs services
maintainers:
- name: Roman Andreev
  email: r.andreev@nixys.io
- name: Anton Zhideev
  email: a.zhideev@nixys.io
- name: Evgenii Tereshkov
  email: evg.krsk@gmail.com
- name: Sergey Lavrinenko
  email: s@lavr.me
- name: Viktor Sokhan
  email: v.sokhan@nixys.io
- name: Ruslan Gainanov
  email: gromrx1@gmail.com
- name: Artem Danielyan
  email: a.danielyan@nixys.io
- name: Roman Emelyanov
  email: r.emelyanov@nixys.io
