releasePrefix: "-"

defaultImage: harbor.cmslabs.ru/cms-labs/api-modules/backend/master
defaultImageTag: ""

generic:
  usePredefinedAffinity: false

services:
  core-backend:
    ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http

deployments:
  core-backend:
    replicas: 2
    containers:
    - name: core-backend
      envSecrets:
      - core-backend-env-list
      ports:
      - name: http
        containerPort: 8080
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "250Mi"
          cpu: "200m"
      startupProbe: 
        httpGet:
          path: /api/docs/index.html
          port: http
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 12
      livenessProbe: 
        httpGet:
          path: /api/docs/index.html
          port: http
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 6
      readinessProbe:
        httpGet:
          path: /api/docs/index.html
          port: http
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 2