defaultImage: harbor.cmslabs.ru/cms-labs/api-modules/frontend/stage

ingresses:
  cms-lab.gubanov.site:
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
    - paths:
      - serviceName: front
        servicePort: http
    extraTls:
    - hosts:
      - cms-lab.gubanov.site
      secretName: "front-tls"