// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "your@mail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/sso/login": {
            "get": {
                "description": "Отправка пользователя с параметрами на сервер аутентификации.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SSO"
                ],
                "summary": "Отправка пользователя с параметрами на сервер аутентификации.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Дополнительные параметры в base64",
                        "name": "extra",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Путь с которого выполнился редирект",
                        "name": "path",
                        "in": "query"
                    }
                ],
                "responses": {
                    "307": {
                        "description": "Temporary Redirect"
                    }
                }
            }
        },
        "/v1/sso/openid": {
            "get": {
                "description": "Дополнительные параметры:",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SSO"
                ],
                "summary": "Второй фактор openid.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID запроса по всему пути аутентификации",
                        "name": "state",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Оригинальный путь по всему пути аутентификации",
                        "name": "path",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Код OTP обмена авторизации",
                        "name": "code",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "ClientID запрашиваемого из аутентификации",
                        "name": "application",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Дополнительные данные с backend base64 по всему пути аутентификации",
                        "name": "extra",
                        "in": "query"
                    }
                ],
                "responses": {
                    "307": {
                        "description": "Temporary Redirect"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/pnet-lab-addon/api",
	Schemes:          []string{},
	Title:            "API",
	Description:      "This is an auto-generated API Docs.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
