core-build:
  stage: build
  extends:
    - .dependencies
    - .releases-branch
  image: $GO_BASE_CI_IMAGE:latest
  needs:
    - golang-test
  script:
    - cd backend
    - echo "Building apiserver bin..."
    - make build
  artifacts:
    expose_as: 'Core build'
    paths:
      - backend/build

core-build-docker:
  stage: build
  extends:
    - .registry_login
    - .releases-branch
  image: ${DOCKER_IMAGE}
  services:
    - ${DOCKER_IMAGE}-dind
  needs:
    - core-build
  script:
    - cd backend
    - echo "Building Docker image..."
    - docker build --no-cache -t $BACKEND_CI_IMAGE:$PIPELINE_VERSION .
    - echo "Pushing Docker image to GitLab Registry..."
    - docker push $BACKEND_CI_IMAGE:$PIPELINE_VERSION
    - echo "Deploying application..."

frontend-build:
  stage: build
  extends:
    - .dependencies
    - .releases-branch
  image: $GO_BASE_CI_IMAGE:latest
  needs:
    - golang-test
  script:
    - cd nextui-dashboard
    - echo "Frontend build static..."
    - yarn build
  artifacts:
    expose_as: 'Front build'
    paths:
      - nextui-dashboard/dist

frontend-build-docker:
  stage: build
  extends:
    - .registry_login
    - .releases-branch
  image: ${DOCKER_IMAGE}
  services:
    - ${DOCKER_IMAGE}-dind
  needs:
    - frontend-build
  script:
    - cd nextui-dashboard
    - echo "Building Docker image..."
    - docker build --no-cache -t $FRONTEND_CI_IMAGE:$PIPELINE_VERSION .
    - echo "Pushing Docker image to GitLab Registry..."
    - docker push $FRONTEND_CI_IMAGE:$PIPELINE_VERSION
    - echo "Deploying application..."


docs-build:
  stage: build
  extends:
    - .registry_login
  only:
    - stage
  image: ${DOCKER_IMAGE}
  services:
    - ${DOCKER_IMAGE}-dind
  needs:
    - golang-test
  script:
    - echo "Building Docker image..."
    - docker build --no-cache -t $DOCS_CI_IMAGE:latest . -f Dockerfile.docs
    - echo "Pushing Docker image to GitLab Registry..."
    - docker push $DOCS_CI_IMAGE:latest
    - echo "Deploying application..."

pnet-lab-addon-build:
  stage: build
  extends:
    - .dependencies
    - .releases-branch
  image: $GO_BASE_CI_IMAGE:latest
  needs:
    - golang-test
  script:
    - cd pnetlabaddon
    - echo "Building pnet lab addon bin..."
    - make build
    - chmod -R 0755 pnetlabaddon
    - dpkg-deb --build pnetlabaddon
    - mv pnetlabaddon.deb pnetlabaddon_$PIPELINE_VERSION_amd64.deb
    - lintian pnetlabaddon_$PIPELINE_VERSION_amd64.deb
    - |
      PACKAGE_NAME="pnetlabaddon_$PIPELINE_VERSION_amd64.deb"
      REGISTRY_URL="https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/generic/${DOCKER_PATH_BRANCH}/${PIPELINE_VERSION}"
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file ${PACKAGE_NAME} ${REGISTRY_URL}/${PACKAGE_NAME}
