core-build:
  stage: build
  extends:
    - .dependencies
    - .releases-branch
  image: $GO_BASE_CI_IMAGE:latest
  needs:
    - golang-test
  script:
    - cd backend
    - echo "Building apiserver bin..."
    - make build
  artifacts:
    expose_as: 'Core build'
    paths:
      - backend/build

core-build-docker:
  stage: build
  extends:
    - .registry_login
    - .releases-branch
  image: ${DOCKER_IMAGE}
  needs:
    - core-build
    - version
  script:
    - cd backend
    - echo "Building Docker image..."
    - VERSION="$(cat ./VERSION)"
    - docker build --no-cache -t $BACKEND_CI_IMAGE:$VERSION  .
    - echo "Pushing Docker image to GitLab Registry..."
    - docker push $BACKEND_CI_IMAGE:$VERSION
    - echo "Deploying application..."

frontend-build:
  stage: build
  extends:
    - .dependencies
    - .releases-branch
  image: $GO_BASE_CI_IMAGE:latest
  needs:
    - golang-test
  script:
    - cd nextui-dashboard
    - echo "Frontend build static..."
    - yarn build
  artifacts:
    expose_as: 'Front build'
    paths:
      - nextui-dashboard/dist

frontend-build-docker:
  stage: build
  extends:
    - .registry_login
    - .releases-branch
  image: ${DOCKER_IMAGE}
  needs:
    - frontend-build
    - version
  script:
    - cd nextui-dashboard
    - echo "Building Docker image..."
    - VERSION="$(cat ./VERSION)"
    - docker build --no-cache -t $FRONTEND_CI_IMAGE:$VERSION  .
    - echo "Pushing Docker image to GitLab Registry..."
    - docker push $FRONTEND_CI_IMAGE:$VERSION
    - echo "Deploying application..."

pnet-lab-addon-build:
  stage: build
  extends:
    - .dependencies
    - .releases-branch
  image: $GO_BASE_CI_IMAGE:latest
  variables:
    PACKAGE_NAME: pnetlab-inject  # Наименование пакета
    PACKAGE_VERSION: ${CI_COMMIT_REF_SLUG}  # Версия пакета
    PROJECT_ID: 50982127  # Идентификатор проекта
  needs:
    - golang-test
  script:
    # Скачать файл
    - |
      curl --fail --header "JOB-TOKEN: ${CI_JOB_TOKEN}" \
           --location \
           --output $PACKAGE_NAME.zip \
           "${CI_API_V4_URL}/projects/$PROJECT_ID/packages/generic/$PACKAGE_NAME/$PACKAGE_VERSION/$PACKAGE_NAME.zip"
    - echo "Пакет успешно скачан pnetlab-inject.zip"
    - mv pnetlab-inject.zip pnetlabaddon/pnetlabaddon/etc/pnetlabaddon/
    - cd pnetlabaddon
    # Собираем пакет
    - echo "Building pnet lab addon bin..."
    - make build
    - chmod -R 0755 pnetlabaddon
    - dpkg-deb --build pnetlabaddon
    - echo "Publishing pnetlabaddon.deb to package registry"
    - 'curl --fail --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file pnetlabaddon.deb "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/pnetlabaddon/${CI_COMMIT_REF_NAME}/pnetlabaddon.deb"'
