services:
  front:
    ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http

deployments:
  front:
    replicas: 1
    initContainers:
    - name: vault-init
      image: harbor.k8s.cmslabs.ru/svc_cms_labs/images/vault-inject
      imageTag: latest
      args:
        - "--path=front"
        - "--output=/var/run/secrets/app"
        - "--formats=sh"
    containers:
    - name: front
      ports:
      - name: http
        containerPort: 80
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "128Mi"
          cpu: "100m"
      startupProbe:
        httpGet:
          path: /
          port: http
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 12
      livenessProbe:
        httpGet:
          path: /
          port: http
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 6
      readinessProbe:
        httpGet:
          path: /
          port: http
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 2